package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// SubmitDraftGeneration is the resolver for the submitDraftGeneration field.
func (r *mutationResolver) SubmitDraftGeneration(ctx context.Context, input SubmitDraftGenerationInput) (*SubmitDraftGenerationResult, error) {
	panic(fmt.Errorf("not implemented: SubmitDraftGeneration - submitDraftGeneration"))
}

// SubmitPolicyReview is the resolver for the submitPolicyReview field.
func (r *mutationResolver) SubmitPolicyReview(ctx context.Context, input SubmitPolicyReviewInput) (*SubmitPolicyReviewResult, error) {
	panic(fmt.Errorf("not implemented: SubmitPolicyReview - submitPolicyReview"))
}

// SubmitPolicyRevision is the resolver for the submitPolicyRevision field.
func (r *mutationResolver) SubmitPolicyRevision(ctx context.Context, input SubmitPolicyRevisionInput) (*SubmitDraftGenerationResult, error) {
	panic(fmt.Errorf("not implemented: SubmitPolicyRevision - submitPolicyRevision"))
}

// SubmitEnrichmentSuggestions is the resolver for the submitEnrichmentSuggestions field.
func (r *mutationResolver) SubmitEnrichmentSuggestions(ctx context.Context, input SubmitEnrichmentSuggestionsInput) (*SubmitDraftGenerationResult, error) {
	panic(fmt.Errorf("not implemented: SubmitEnrichmentSuggestions - submitEnrichmentSuggestions"))
}

// SetAIEnabled is the resolver for the setAIEnabled field.
func (r *mutationResolver) SetAIEnabled(ctx context.Context, enabled bool) (bool, error) {
	panic(fmt.Errorf("not implemented: SetAIEnabled - setAIEnabled"))
}

// SetAIToken is the resolver for the setAIToken field.
func (r *mutationResolver) SetAIToken(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: SetAIToken - setAIToken"))
}

// SetAIModel is the resolver for the setAIModel field.
func (r *mutationResolver) SetAIModel(ctx context.Context, modelID string) (bool, error) {
	panic(fmt.Errorf("not implemented: SetAIModel - setAIModel"))
}

// SetAIRetrievalConfig is the resolver for the setAIRetrievalConfig field.
func (r *mutationResolver) SetAIRetrievalConfig(ctx context.Context, topK int) (*AIRetrievalConfig, error) {
	panic(fmt.Errorf("not implemented: SetAIRetrievalConfig - setAIRetrievalConfig"))
}

// SetUserAiQueryLimit is the resolver for the setUserAiQueryLimit field.
func (r *mutationResolver) SetUserAiQueryLimit(ctx context.Context, userID string, limit int) (*AIUserQueryLimit, error) {
	panic(fmt.Errorf("not implemented: SetUserAiQueryLimit - setUserAiQueryLimit"))
}

// SearchAndAnswer is the resolver for the searchAndAnswer field.
func (r *queryResolver) SearchAndAnswer(ctx context.Context, question string, groupID *string) (*SearchAndAnswerResult, error) {
	panic(fmt.Errorf("not implemented: SearchAndAnswer - searchAndAnswer"))
}

// AuthoringAssist is the resolver for the authoringAssist field.
func (r *queryResolver) AuthoringAssist(ctx context.Context, input AuthoringAssistInput) (*AuthoringAssistResult, error) {
	panic(fmt.Errorf("not implemented: AuthoringAssist - authoringAssist"))
}

// AiJob is the resolver for the aiJob field.
func (r *queryResolver) AiJob(ctx context.Context, jobID string) (*AIJobStatus, error) {
	panic(fmt.Errorf("not implemented: AiJob - aiJob"))
}

// TopPolicyQuestions is the resolver for the topPolicyQuestions field.
func (r *queryResolver) TopPolicyQuestions(ctx context.Context, limit *int) ([]string, error) {
	panic(fmt.Errorf("not implemented: TopPolicyQuestions - topPolicyQuestions"))
}

// PolicyVersionSummary is the resolver for the policyVersionSummary field.
func (r *queryResolver) PolicyVersionSummary(ctx context.Context, versionID string) (*PolicySummaryResult, error) {
	panic(fmt.Errorf("not implemented: PolicyVersionSummary - policyVersionSummary"))
}

// RelatedPolicySuggestions is the resolver for the relatedPolicySuggestions field.
func (r *queryResolver) RelatedPolicySuggestions(ctx context.Context, policyID string, first *int) ([]*RelatedPolicySuggestion, error) {
	panic(fmt.Errorf("not implemented: RelatedPolicySuggestions - relatedPolicySuggestions"))
}

// AiJobResultContent is the resolver for the aiJobResultContent field.
func (r *queryResolver) AiJobResultContent(ctx context.Context, resultRef string) (*AIJobResultContent, error) {
	panic(fmt.Errorf("not implemented: AiJobResultContent - aiJobResultContent"))
}

// AiHealth is the resolver for the aiHealth field.
func (r *queryResolver) AiHealth(ctx context.Context) (*AIHealth, error) {
	panic(fmt.Errorf("not implemented: AiHealth - aiHealth"))
}

// AiEnabled is the resolver for the aiEnabled field.
func (r *queryResolver) AiEnabled(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: AiEnabled - aiEnabled"))
}

// AiTokenSet is the resolver for the aiTokenSet field.
func (r *queryResolver) AiTokenSet(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: AiTokenSet - aiTokenSet"))
}

// AiModel is the resolver for the aiModel field.
func (r *queryResolver) AiModel(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: AiModel - aiModel"))
}

// AiRetrievalConfig is the resolver for the aiRetrievalConfig field.
func (r *queryResolver) AiRetrievalConfig(ctx context.Context) (*AIRetrievalConfig, error) {
	panic(fmt.Errorf("not implemented: AiRetrievalConfig - aiRetrievalConfig"))
}

// AiJobResult is the resolver for the aiJobResult field.
func (r *subscriptionResolver) AiJobResult(ctx context.Context, jobID string) (<-chan *AIJobResult, error) {
	panic(fmt.Errorf("not implemented: AiJobResult - aiJobResult"))
}
