// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// SubmitDraftGeneration is the resolver for the submitDraftGeneration field.
func (r *mutationResolver) SubmitDraftGeneration(ctx context.Context, input SubmitDraftGenerationInput) (*SubmitDraftGenerationResult, error) {
	return SubmitDraftGenerationResolver(ctx, r.AIClient, r.CategoryClient, r.enrichmentResolver(), input)
}

// SubmitPolicyReview is the resolver for the submitPolicyReview field.
func (r *mutationResolver) SubmitPolicyReview(ctx context.Context, input SubmitPolicyReviewInput) (*SubmitPolicyReviewResult, error) {
	return SubmitPolicyReviewResolver(ctx, r.AIClient, r.CategoryClient, r.enrichmentResolver(), input)
}

// SubmitPolicyRevision is the resolver for the submitPolicyRevision field.
func (r *mutationResolver) SubmitPolicyRevision(ctx context.Context, input SubmitPolicyRevisionInput) (*SubmitDraftGenerationResult, error) {
	return SubmitPolicyRevisionResolver(ctx, r.AIClient, r.CategoryClient, r.enrichmentResolver(), input)
}

// SubmitEnrichmentSuggestions is the resolver for the submitEnrichmentSuggestions field.
func (r *mutationResolver) SubmitEnrichmentSuggestions(ctx context.Context, input SubmitEnrichmentSuggestionsInput) (*SubmitDraftGenerationResult, error) {
	return SubmitEnrichmentSuggestionsResolver(ctx, r.AIClient, r.CategoryClient, r.enrichmentResolver(), input)
}

// SetAIEnabled is the resolver for the setAIEnabled field.
func (r *mutationResolver) SetAIEnabled(ctx context.Context, enabled bool) (bool, error) {
	return SetAIEnabledResolver(ctx, r.AIClient, enabled)
}

// SetAIProviderConfig is the resolver for the setAIProviderConfig field.
func (r *mutationResolver) SetAIProviderConfig(ctx context.Context, input AIProviderConfigInput) (*AIConfig, error) {
	return SetAIProviderConfigResolver(ctx, r.AIClient, input)
}

// SetAIProviderCredential is the resolver for the setAIProviderCredential field.
func (r *mutationResolver) SetAIProviderCredential(ctx context.Context, credential string) (*AICredentialStatus, error) {
	return SetAIProviderCredentialResolver(ctx, r.AIClient, credential)
}

// TestAIProvider is the resolver for the testAIProvider field.
func (r *mutationResolver) TestAIProvider(ctx context.Context) (*AIProviderTestResult, error) {
	return TestAIProviderResolver(ctx, r.AIClient)
}

// AcceptAIDataNotice is the resolver for the acceptAIDataNotice field.
func (r *mutationResolver) AcceptAIDataNotice(ctx context.Context, noticeVersion string) (*AIDataNotice, error) {
	return AcceptAIDataNoticeResolver(ctx, r.AIClient, noticeVersion)
}

// SetAIRetrievalConfig is the resolver for the setAIRetrievalConfig field.
func (r *mutationResolver) SetAIRetrievalConfig(ctx context.Context, topK int) (*AIRetrievalConfig, error) {
	return SetAIRetrievalConfigResolver(ctx, r.AIClient, topK)
}

// SetUserAiQueryLimit is the resolver for the setUserAiQueryLimit field.
func (r *mutationResolver) SetUserAiQueryLimit(ctx context.Context, userID string, limit int) (*AIUserQueryLimit, error) {
	return SetUserAiQueryLimitResolver(ctx, r.AIClient, userID, limit)
}

// SearchAndAnswer is the resolver for the searchAndAnswer field.
func (r *queryResolver) SearchAndAnswer(ctx context.Context, question string, categoryID *string) (*SearchAndAnswerResult, error) {
	return SearchAndAnswerResolver(ctx, r.AIClient, r.CategoryClient, question, categoryID)
}

// AuthoringAssist is the resolver for the authoringAssist field.
func (r *queryResolver) AuthoringAssist(ctx context.Context, input AuthoringAssistInput) (*AuthoringAssistResult, error) {
	return AuthoringAssistResolver(ctx, r.AIClient, input)
}

// AiJob is the resolver for the aiJob field.
func (r *queryResolver) AiJob(ctx context.Context, jobID string) (*AIJobStatus, error) {
	return AIJobStatusResolver(ctx, r.AIClient, jobID)
}

// TopPolicyQuestions is the resolver for the topPolicyQuestions field.
func (r *queryResolver) TopPolicyQuestions(ctx context.Context, limit *int) ([]string, error) {
	return TopPolicyQuestionsResolver(ctx, r.AIClient, limit)
}

// PolicyVersionSummary is the resolver for the policyVersionSummary field.
func (r *queryResolver) PolicyVersionSummary(ctx context.Context, versionID string) (*PolicySummaryResult, error) {
	return PolicyVersionSummaryResolver(ctx, r.AIClient, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, versionID)
}

// RelatedPolicySuggestions is the resolver for the relatedPolicySuggestions field.
func (r *queryResolver) RelatedPolicySuggestions(ctx context.Context, policyID string, first *int) ([]*RelatedPolicySuggestion, error) {
	return RelatedPolicySuggestionsResolver(ctx, r.AIClient, r.CategoryClient, policyID, first)
}

// AiJobResultContent is the resolver for the aiJobResultContent field.
func (r *queryResolver) AiJobResultContent(ctx context.Context, resultRef string) (*AIJobResultContent, error) {
	return AIJobResultContentResolver(ctx, r.AIJobContentReader, resultRef)
}

// AiHealth is the resolver for the aiHealth field.
func (r *queryResolver) AiHealth(ctx context.Context) (*AIHealth, error) {
	return AIHealthResolver(ctx, r.AIClient)
}

// AiEnabled is the resolver for the aiEnabled field.
func (r *queryResolver) AiEnabled(ctx context.Context) (bool, error) {
	return AIEnabledResolver(ctx, r.AIClient)
}

// AiConfig is the resolver for the aiConfig field.
func (r *queryResolver) AiConfig(ctx context.Context) (*AIConfig, error) {
	return AIConfigResolver(ctx, r.AIClient)
}

// AiRetrievalConfig is the resolver for the aiRetrievalConfig field.
func (r *queryResolver) AiRetrievalConfig(ctx context.Context) (*AIRetrievalConfig, error) {
	return AIRetrievalConfigResolver(ctx, r.AIClient)
}

// AiJobResult is the resolver for the aiJobResult field.
func (r *subscriptionResolver) AiJobResult(ctx context.Context, jobID string) (<-chan *AIJobResult, error) {
	return AIJobResultResolver(ctx, r.AIClient, r.AIJobBroker, jobID)
}
