// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, tier *string, groupID *string, actorUserID *string, subject *string, pageSize *int, pageToken *string) (*AuditQueryPage, error) {
	return QueryAuditLogResolver(ctx, r.AuditClient, r.IdentityClient, r.CategoryClient, r.PolicyClient, r.TemplateClient, tier, groupID, actorUserID, subject, pageSize, pageToken)
}

// AuditSegment is the resolver for the auditSegment field.
func (r *queryResolver) AuditSegment(ctx context.Context, fromRecordID string, toRecordID string) (*AuditSegment, error) {
	return ExportAuditSegmentResolver(ctx, r.AuditClient, fromRecordID, toRecordID)
}

// VerifyAuditChain is the resolver for the verifyAuditChain field.
func (r *queryResolver) VerifyAuditChain(ctx context.Context, fromRecordID string, toRecordID string) (*AuditChainVerification, error) {
	return VerifyAuditChainResolver(ctx, r.AuditClient, r.IdentityClient, fromRecordID, toRecordID)
}
