// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, tier *string, groupID *string, actorUserID *string, subject *string, pageSize *int, pageToken *string) (*AuditQueryPage, error) {
	panic(fmt.Errorf("not implemented: AuditLog - auditLog"))
}

// AuditSegment is the resolver for the auditSegment field.
func (r *queryResolver) AuditSegment(ctx context.Context, fromRecordID string, toRecordID string) (*AuditSegment, error) {
	panic(fmt.Errorf("not implemented: AuditSegment - auditSegment"))
}

// VerifyAuditChain is the resolver for the verifyAuditChain field.
func (r *queryResolver) VerifyAuditChain(ctx context.Context, fromRecordID string, toRecordID string) (*AuditChainVerification, error) {
	panic(fmt.Errorf("not implemented: VerifyAuditChain - verifyAuditChain"))
}
