// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// IssueCollabToken is the resolver for the issueCollabToken field.
func (r *mutationResolver) IssueCollabToken(ctx context.Context, input IssueCollabTokenInput) (*IssueCollabTokenPayload, error) {
	return IssueCollabToken(ctx, r.CollabClient, r.PolicyClient, r.CategoryClient, input)
}
