// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, name string, slug string, parentID *string) (*Category, error) {
	return CreateCategory(ctx, r.CategoryClient, name, slug, parentID)
}

// SetCategoryDefaults is the resolver for the setCategoryDefaults field.
func (r *mutationResolver) SetCategoryDefaults(ctx context.Context, id string, defaultTemplateID *string, defaultWorkflowID *string, defaultTemplateNone *bool) (*Category, error) {
	return SetCategoryDefaults(ctx, r.CategoryClient, id, defaultTemplateID, defaultWorkflowID, defaultTemplateNone)
}

// RenameCategory is the resolver for the renameCategory field.
func (r *mutationResolver) RenameCategory(ctx context.Context, id string, name string, slug string) (*Category, error) {
	return RenameCategory(ctx, r.CategoryClient, id, name, slug)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	return DeleteCategory(ctx, r.CategoryClient, id)
}

// MoveCategory is the resolver for the moveCategory field.
func (r *mutationResolver) MoveCategory(ctx context.Context, categoryID string, newParentID *string) (*Category, error) {
	return MoveCategory(ctx, r.CategoryClient, categoryID, newParentID)
}

// CreateTemplate is the resolver for the createTemplate field.
func (r *mutationResolver) CreateTemplate(ctx context.Context, name string, ownerCategoryID *string) (*Template, error) {
	return CreateTemplate(ctx, r.TemplateClient, name, ownerCategoryID)
}

// CreateTemplateVersion is the resolver for the createTemplateVersion field.
func (r *mutationResolver) CreateTemplateVersion(ctx context.Context, templateID string, sections []*SectionInput) (*TemplateVersion, error) {
	return CreateTemplateVersion(ctx, r.TemplateClient, templateID, sections)
}

// UpdateTemplateVersionSections is the resolver for the updateTemplateVersionSections field.
func (r *mutationResolver) UpdateTemplateVersionSections(ctx context.Context, id string, sections []*SectionInput) (*TemplateVersion, error) {
	return UpdateTemplateVersionSections(ctx, r.TemplateClient, id, sections)
}

// PublishTemplateVersion is the resolver for the publishTemplateVersion field.
func (r *mutationResolver) PublishTemplateVersion(ctx context.Context, id string) (*TemplateVersion, error) {
	return PublishTemplateVersion(ctx, r.TemplateClient, id)
}

// DiscardTemplateVersion is the resolver for the discardTemplateVersion field.
func (r *mutationResolver) DiscardTemplateVersion(ctx context.Context, id string) (bool, error) {
	if err := DiscardTemplateVersion(ctx, r.TemplateClient, id); err != nil {
		return false, err
	}
	return true, nil
}

// RetireTemplate is the resolver for the retireTemplate field.
func (r *mutationResolver) RetireTemplate(ctx context.Context, id string) (*Template, error) {
	return RetireTemplate(ctx, r.TemplateClient, id)
}

// DeleteTemplate is the resolver for the deleteTemplate field.
func (r *mutationResolver) DeleteTemplate(ctx context.Context, id string) (bool, error) {
	if !r.AllowHardDelete {
		return false, status.Error(codes.FailedPrecondition, "hard delete is disabled; retire the template instead")
	}
	if err := DeleteTemplate(ctx, r.TemplateClient, id); err != nil {
		return false, err
	}
	return true, nil
}

// RenameTemplate is the resolver for the renameTemplate field.
func (r *mutationResolver) RenameTemplate(ctx context.Context, id string, name string) (*Template, error) {
	return RenameTemplate(ctx, r.TemplateClient, id, name)
}

// CreatePolicy is the resolver for the createPolicy field.
func (r *mutationResolver) CreatePolicy(ctx context.Context, homeCategoryID string, title string, sensitivity Sensitivity, templateID *string, documentType *DocumentType) (*Policy, error) {
	return CreatePolicy(ctx, r.PolicyClient, r.CategoryClient, homeCategoryID, title, sensitivity, templateID, documentType)
}

// SaveDraft is the resolver for the saveDraft field.
func (r *mutationResolver) SaveDraft(ctx context.Context, policyID string, contentJSON string, templateVersionID *string) (*PolicyVersion, error) {
	return SaveDraft(ctx, r.PolicyClient, r.CategoryClient, policyID, contentJSON, derefOrEmpty(templateVersionID))
}

// SetPolicyTemplate is the resolver for the setPolicyTemplate field.
func (r *mutationResolver) SetPolicyTemplate(ctx context.Context, policyID string, templateID *string, none bool) (*Policy, error) {
	return SetPolicyTemplate(ctx, r.PolicyClient, r.CategoryClient, policyID, templateID, none)
}

// PublishDraft is the resolver for the publishDraft field.
func (r *mutationResolver) PublishDraft(ctx context.Context, policyID string) (*PolicyVersion, error) {
	return PublishDraft(ctx, r.logger().Ctx(ctx), r.PolicyClient, r.CategoryClient, r.CollabRoomClient, policyID)
}

// DiscardDraft is the resolver for the discardDraft field.
func (r *mutationResolver) DiscardDraft(ctx context.Context, policyID string) (bool, error) {
	return DiscardDraft(ctx, r.PolicyClient, r.CategoryClient, policyID)
}

// DeletePolicy is the resolver for the deletePolicy field.
func (r *mutationResolver) DeletePolicy(ctx context.Context, id string) (bool, error) {
	return DeletePolicy(ctx, r.PolicyClient, r.CategoryClient, id)
}

// RetirePolicy is the resolver for the retirePolicy field.
func (r *mutationResolver) RetirePolicy(ctx context.Context, id string) (*Policy, error) {
	return RetirePolicy(ctx, r.PolicyClient, r.CategoryClient, id)
}

// SetPolicyOwner is the resolver for the setPolicyOwner field.
func (r *mutationResolver) SetPolicyOwner(ctx context.Context, policyID string, ownerUserID string) (*Policy, error) {
	return SetPolicyOwner(ctx, r.PolicyClient, policyID, ownerUserID)
}

// MovePolicy is the resolver for the movePolicy field.
func (r *mutationResolver) MovePolicy(ctx context.Context, policyID string, homeCategoryID string) (*Policy, error) {
	return MovePolicy(ctx, r.PolicyClient, policyID, homeCategoryID)
}

// SetPolicySensitivity is the resolver for the setPolicySensitivity field.
func (r *mutationResolver) SetPolicySensitivity(ctx context.Context, policyID string, sensitivity Sensitivity) (*Policy, error) {
	return SetPolicySensitivity(ctx, r.PolicyClient, r.CategoryClient, policyID, sensitivity)
}

// RenamePolicy is the resolver for the renamePolicy field.
func (r *mutationResolver) RenamePolicy(ctx context.Context, policyID string, newTitle string) (*RenamePolicyResult, error) {
	return RenamePolicy(ctx, r.PolicyClient, r.CategoryClient, r.WorkflowClient, policyID, newTitle)
}

// BreakGlassReveal is the resolver for the breakGlassReveal field.
func (r *mutationResolver) BreakGlassReveal(ctx context.Context, policyID string, reason string) (*BreakGlassResult, error) {
	return BreakGlassRevealResolver(ctx, r.IdentityAdminClient, r.PolicyClient, policyID, reason)
}

// ReindexPolicy is the resolver for the reindexPolicy field.
func (r *mutationResolver) ReindexPolicy(ctx context.Context, policyID string) (*ReindexResult, error) {
	return ReindexPolicy(ctx, r.PolicyClient, policyID)
}

// ReindexPolicyVersion is the resolver for the reindexPolicyVersion field.
func (r *mutationResolver) ReindexPolicyVersion(ctx context.Context, policyVersionID string) (*ReindexResult, error) {
	return ReindexPolicyVersion(ctx, r.PolicyClient, policyVersionID)
}

// SetCategoryGovernance is the resolver for the setCategoryGovernance field.
func (r *mutationResolver) SetCategoryGovernance(ctx context.Context, id string, owners []string, idpGroupIds []string, exclusionGroupIds []string, ackTriggers AckTrigger, reviewCadence ReviewCadence, reviewDate *string, ackEveryone *bool) (*Category, error) {
	return SetCategoryGovernance(ctx, r.CategoryClient, id, owners, idpGroupIds, exclusionGroupIds, ackTriggers, reviewCadence, reviewDate, ackEveryone)
}

// SetPolicyAck is the resolver for the setPolicyAck field.
func (r *mutationResolver) SetPolicyAck(ctx context.Context, policyID string, ackTriggers *AckTrigger, ackAudienceOverride []string) (*Policy, error) {
	return SetPolicyAck(ctx, r.PolicyClient, policyID, ackTriggers, ackAudienceOverride)
}

// SetGlobalSettings is the resolver for the setGlobalSettings field.
func (r *mutationResolver) SetGlobalSettings(ctx context.Context, input GlobalSettingsInput) (*GlobalSettings, error) {
	return SetGlobalSettings(ctx, r.SettingsClient, input)
}

// SetEmailServiceConfig is the resolver for the setEmailServiceConfig field.
func (r *mutationResolver) SetEmailServiceConfig(ctx context.Context, input EmailServiceConfigInput) (*EmailServiceConfigStatus, error) {
	return SetEmailServiceConfig(ctx, r.SettingsClient, input)
}

// AddAppendix is the resolver for the addAppendix field.
func (r *mutationResolver) AddAppendix(ctx context.Context, policyVersionID string, title string, contentJSON string) (*Appendix, error) {
	return AddAppendixResolver(ctx, r.AppendixClient, policyVersionID, title, contentJSON)
}

// UpdateAppendix is the resolver for the updateAppendix field.
func (r *mutationResolver) UpdateAppendix(ctx context.Context, id string, title string, contentJSON string) (*Appendix, error) {
	return UpdateAppendixResolver(ctx, r.AppendixClient, id, title, contentJSON)
}

// ReorderAppendices is the resolver for the reorderAppendices field.
func (r *mutationResolver) ReorderAppendices(ctx context.Context, policyVersionID string, orderedIds []string) ([]*Appendix, error) {
	return ReorderAppendicesResolver(ctx, r.AppendixClient, policyVersionID, orderedIds)
}

// DeleteAppendix is the resolver for the deleteAppendix field.
func (r *mutationResolver) DeleteAppendix(ctx context.Context, id string) (bool, error) {
	return DeleteAppendixResolver(ctx, r.AppendixClient, id)
}

// SetRelatedPolicies is the resolver for the setRelatedPolicies field.
func (r *mutationResolver) SetRelatedPolicies(ctx context.Context, policyID string, relatedPolicyIds []string) ([]*RelatedPolicy, error) {
	return SetRelatedPoliciesResolver(ctx, r.logger(), r.RelationClient, r.PolicyClient, r.CategoryClient, r.IdentityClient, policyID, relatedPolicyIds)
}

// CreateContactBlock is the resolver for the createContactBlock field.
func (r *mutationResolver) CreateContactBlock(ctx context.Context, block ContactBlockInput) (*ContactBlock, error) {
	return CreateContactBlockResolver(ctx, r.ContactClient, &block)
}

// UpdateContactBlock is the resolver for the updateContactBlock field.
func (r *mutationResolver) UpdateContactBlock(ctx context.Context, id string, block ContactBlockInput) (*ContactBlock, error) {
	return UpdateContactBlockResolver(ctx, r.ContactClient, id, &block)
}

// DeleteContactBlock is the resolver for the deleteContactBlock field.
func (r *mutationResolver) DeleteContactBlock(ctx context.Context, id string) (bool, error) {
	return DeleteContactBlockResolver(ctx, r.ContactClient, id)
}

// SetContactBlockArchived is the resolver for the setContactBlockArchived field.
func (r *mutationResolver) SetContactBlockArchived(ctx context.Context, id string, archived bool) (*ContactBlock, error) {
	return SetContactBlockArchivedResolver(ctx, r.ContactClient, id, archived)
}

// SetPolicyContactBlocks is the resolver for the setPolicyContactBlocks field.
func (r *mutationResolver) SetPolicyContactBlocks(ctx context.Context, policyID string, contactBlockIds []string) ([]*ContactBlock, error) {
	return SetPolicyContactBlocksResolver(ctx, r.ContactClient, policyID, contactBlockIds)
}

// CreateReference is the resolver for the createReference field.
func (r *mutationResolver) CreateReference(ctx context.Context, input ReferenceInput) (*Reference, error) {
	return CreateReferenceResolver(ctx, r.ReferenceClient, &input)
}

// UpdateReference is the resolver for the updateReference field.
func (r *mutationResolver) UpdateReference(ctx context.Context, id string, input ReferenceInput) (*Reference, error) {
	return UpdateReferenceResolver(ctx, r.ReferenceClient, id, &input)
}

// DeleteReference is the resolver for the deleteReference field.
func (r *mutationResolver) DeleteReference(ctx context.Context, id string) (bool, error) {
	return DeleteReferenceResolver(ctx, r.ReferenceClient, id)
}

// SetReferenceArchived is the resolver for the setReferenceArchived field.
func (r *mutationResolver) SetReferenceArchived(ctx context.Context, id string, archived bool) (*Reference, error) {
	return SetReferenceArchivedResolver(ctx, r.ReferenceClient, id, archived)
}

// SetPolicyReferences is the resolver for the setPolicyReferences field.
func (r *mutationResolver) SetPolicyReferences(ctx context.Context, policyID string, referenceIds []string) ([]*Reference, error) {
	return SetPolicyReferencesResolver(ctx, r.ReferenceClient, r.PolicyClient, r.CategoryClient, policyID, referenceIds)
}

// CreateDefinition is the resolver for the createDefinition field.
func (r *mutationResolver) CreateDefinition(ctx context.Context, input DefinitionEntryInput) (*DefinitionEntry, error) {
	return CreateDefinitionResolver(ctx, r.DefinitionLibraryClient, &input)
}

// UpdateDefinition is the resolver for the updateDefinition field.
func (r *mutationResolver) UpdateDefinition(ctx context.Context, id string, input DefinitionEntryInput) (*DefinitionEntry, error) {
	return UpdateDefinitionResolver(ctx, r.DefinitionLibraryClient, id, &input)
}

// DeleteDefinition is the resolver for the deleteDefinition field.
func (r *mutationResolver) DeleteDefinition(ctx context.Context, id string) (bool, error) {
	return DeleteDefinitionResolver(ctx, r.DefinitionLibraryClient, id)
}

// SetDefinitionArchived is the resolver for the setDefinitionArchived field.
func (r *mutationResolver) SetDefinitionArchived(ctx context.Context, id string, archived bool) (*DefinitionEntry, error) {
	return SetDefinitionArchivedResolver(ctx, r.DefinitionLibraryClient, id, archived)
}

// SetPolicyDefinitionEntries is the resolver for the setPolicyDefinitionEntries field.
func (r *mutationResolver) SetPolicyDefinitionEntries(ctx context.Context, policyID string, definitionIds []string) ([]*DefinitionEntry, error) {
	return SetPolicyDefinitionEntriesResolver(ctx, r.DefinitionLibraryClient, r.PolicyClient, r.CategoryClient, policyID, definitionIds)
}

// SetCategoryRuleset is the resolver for the setCategoryRuleset field.
func (r *mutationResolver) SetCategoryRuleset(ctx context.Context, categoryID string, rules []*RaciRuleInput) (*CategoryRuleset, error) {
	return SetCategoryRulesetResolver(ctx, r.CategoryClient, categoryID, rules)
}

// Appendices is the resolver for the appendices field.
func (r *policyVersionResolver) Appendices(ctx context.Context, obj *PolicyVersion) ([]*Appendix, error) {
	return AppendicesForVersion(ctx, r.AppendixClient, obj.ID)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*Category, error) {
	return GetCategory(ctx, r.CategoryClient, id)
}

// CategoryChildren is the resolver for the categoryChildren field.
func (r *queryResolver) CategoryChildren(ctx context.Context, parentID *string) ([]*Category, error) {
	return ListCategoryChildren(ctx, r.CategoryClient, parentID)
}

// CategoryTree is the resolver for the categoryTree field.
func (r *queryResolver) CategoryTree(ctx context.Context, rootID *string) ([]*Category, error) {
	return CategoryTree(ctx, r.CategoryClient, rootID)
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, ownerCategoryID *string) ([]*Template, error) {
	return ListTemplates(ctx, r.TemplateClient, r.CategoryClient, ownerCategoryID)
}

// LatestTemplateVersion is the resolver for the latestTemplateVersion field.
func (r *queryResolver) LatestTemplateVersion(ctx context.Context, templateID string) (*TemplateVersion, error) {
	return LatestTemplateVersion(ctx, r.TemplateClient, r.CategoryClient, templateID)
}

// TemplateVersions is the resolver for the templateVersions field.
func (r *queryResolver) TemplateVersions(ctx context.Context, templateID string) ([]*TemplateVersion, error) {
	return ListTemplateVersions(ctx, r.TemplateClient, r.CategoryClient, templateID)
}

// Policy is the resolver for the policy field.
func (r *queryResolver) Policy(ctx context.Context, id string) (*Policy, error) {
	return GetPolicy(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, r.IdentityClient, id)
}

// PolicyByNumber is the resolver for the policyByNumber field.
func (r *queryResolver) PolicyByNumber(ctx context.Context, number string) (*Policy, error) {
	return PolicyByNumber(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, r.IdentityClient, number)
}

// Policies is the resolver for the policies field.
func (r *queryResolver) Policies(ctx context.Context, categoryID string, includeDescendants *bool, documentType *DocumentType) ([]*Policy, error) {
	return ListPolicies(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, r.IdentityClient, categoryID, includeDescendants, documentType)
}

// PolicyVersion is the resolver for the policyVersion field.
func (r *queryResolver) PolicyVersion(ctx context.Context, id string) (*PolicyVersion, error) {
	return GetPolicyVersion(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, id)
}

// PolicyVersions is the resolver for the policyVersions field.
func (r *queryResolver) PolicyVersions(ctx context.Context, policyID string) ([]*PolicyVersion, error) {
	return ListPolicyVersions(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, policyID)
}

// DiffVersions is the resolver for the diffVersions field.
func (r *queryResolver) DiffVersions(ctx context.Context, fromVersionID string, toVersionID string) ([]*SectionDiff, error) {
	return DiffVersions(ctx, r.PolicyClient, fromVersionID, toVersionID)
}

// EffectiveTemplate is the resolver for the effectiveTemplate field.
func (r *queryResolver) EffectiveTemplate(ctx context.Context, policyID string) (*EffectiveTemplate, error) {
	return GetEffectiveTemplate(ctx, r.PolicyClient, policyID)
}

// EffectiveGovernance is the resolver for the effectiveGovernance field.
func (r *queryResolver) EffectiveGovernance(ctx context.Context, categoryID string) (*EffectiveGovernance, error) {
	return GetEffectiveGovernance(ctx, r.CategoryClient, categoryID)
}

// GlobalSettings is the resolver for the globalSettings field.
func (r *queryResolver) GlobalSettings(ctx context.Context) (*GlobalSettings, error) {
	return GetGlobalSettings(ctx, r.SettingsClient)
}

// EmailServiceConfig is the resolver for the emailServiceConfig field.
func (r *queryResolver) EmailServiceConfig(ctx context.Context) (*EmailServiceConfigStatus, error) {
	return GetEmailServiceConfig(ctx, r.SettingsClient)
}

// RelatedPolicies is the resolver for the relatedPolicies field.
func (r *queryResolver) RelatedPolicies(ctx context.Context, policyID string) ([]*RelatedPolicy, error) {
	return RelatedPoliciesResolver(ctx, r.RelationClient, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, r.IdentityClient, policyID)
}

// RelatedPolicyCandidates is the resolver for the relatedPolicyCandidates field.
func (r *queryResolver) RelatedPolicyCandidates(ctx context.Context, policyID string) ([]*Policy, error) {
	return RelatedPolicyCandidatesResolver(ctx, r.Resolver, policyID)
}

// ContactBlocks is the resolver for the contactBlocks field.
func (r *queryResolver) ContactBlocks(ctx context.Context, includeArchived *bool) ([]*ContactBlock, error) {
	return ContactBlocksResolver(ctx, r.ContactClient, includeArchived != nil && *includeArchived)
}

// PolicyContactBlocks is the resolver for the policyContactBlocks field.
func (r *queryResolver) PolicyContactBlocks(ctx context.Context, policyID string) ([]*ContactBlock, error) {
	return PolicyContactBlocksResolver(ctx, r.ContactClient, policyID)
}

// References is the resolver for the references field.
func (r *queryResolver) References(ctx context.Context, includeArchived *bool) ([]*Reference, error) {
	return ReferencesResolver(ctx, r.ReferenceClient, includeArchived != nil && *includeArchived)
}

// PolicyReferences is the resolver for the policyReferences field.
func (r *queryResolver) PolicyReferences(ctx context.Context, policyID string) ([]*Reference, error) {
	return PolicyReferencesResolver(ctx, r.ReferenceClient, policyID)
}

// Definitions is the resolver for the definitions field.
func (r *queryResolver) Definitions(ctx context.Context, categoryID *string, includeArchived *bool) ([]*DefinitionEntry, error) {
	return DefinitionLibraryResolver(ctx, r.DefinitionLibraryClient, categoryID, includeArchived != nil && *includeArchived)
}

// PolicyDefinitionCandidates is the resolver for the policyDefinitionCandidates field.
func (r *queryResolver) PolicyDefinitionCandidates(ctx context.Context, policyID string, includeArchived *bool) ([]*DefinitionEntry, error) {
	return PolicyDefinitionCandidatesResolver(ctx, r.DefinitionLibraryClient, policyID, includeArchived != nil && *includeArchived)
}

// PolicyDefinitionEntries is the resolver for the policyDefinitionEntries field.
func (r *queryResolver) PolicyDefinitionEntries(ctx context.Context, policyID string) ([]*DefinitionEntry, error) {
	return PolicyDefinitionEntriesResolver(ctx, r.DefinitionLibraryClient, policyID)
}

// CategoryRuleset is the resolver for the categoryRuleset field.
func (r *queryResolver) CategoryRuleset(ctx context.Context, categoryID string) (*CategoryRuleset, error) {
	return GetCategoryRulesetResolver(ctx, r.CategoryClient, categoryID)
}

// SimulateCategory is the resolver for the simulateCategory field.
func (r *queryResolver) SimulateCategory(ctx context.Context, categoryID string, userID string, draftRules []*RaciRuleInput) (*RaciDecision, error) {
	return SimulateCategoryResolver(ctx, r.Resolver, categoryID, userID, draftRules)
}

// CategoryApprovers is the resolver for the categoryApprovers field.
func (r *queryResolver) CategoryApprovers(ctx context.Context, categoryID string) ([]*User, error) {
	return CategoryApproversResolver(ctx, r.Resolver, categoryID)
}

// ViewerIsApprover is the resolver for the viewerIsApprover field.
func (r *queryResolver) ViewerIsApprover(ctx context.Context) (bool, error) {
	return ViewerIsApproverResolver(ctx, r.logger(), r.CategoryClient)
}

// PolicyVersion returns PolicyVersionResolver implementation.
func (r *Resolver) PolicyVersion() PolicyVersionResolver { return &policyVersionResolver{r} }

type policyVersionResolver struct{ *Resolver }
