// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, name string, slug string, parentID *string) (*Group, error) {
	panic(fmt.Errorf("not implemented: CreateGroup - createGroup"))
}

// SetGroupDefaults is the resolver for the setGroupDefaults field.
func (r *mutationResolver) SetGroupDefaults(ctx context.Context, id string, defaultTemplateID *string, defaultWorkflowID *string, defaultTemplateNone *bool) (*Group, error) {
	panic(fmt.Errorf("not implemented: SetGroupDefaults - setGroupDefaults"))
}

// RenameGroup is the resolver for the renameGroup field.
func (r *mutationResolver) RenameGroup(ctx context.Context, id string, name string, slug string) (*Group, error) {
	panic(fmt.Errorf("not implemented: RenameGroup - renameGroup"))
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGroup - deleteGroup"))
}

// MoveGroup is the resolver for the moveGroup field.
func (r *mutationResolver) MoveGroup(ctx context.Context, groupID string, newParentID *string) (*Group, error) {
	panic(fmt.Errorf("not implemented: MoveGroup - moveGroup"))
}

// CreateTemplate is the resolver for the createTemplate field.
func (r *mutationResolver) CreateTemplate(ctx context.Context, name string, ownerGroupID *string) (*Template, error) {
	panic(fmt.Errorf("not implemented: CreateTemplate - createTemplate"))
}

// CreateTemplateVersion is the resolver for the createTemplateVersion field.
func (r *mutationResolver) CreateTemplateVersion(ctx context.Context, templateID string, sections []*SectionInput) (*TemplateVersion, error) {
	panic(fmt.Errorf("not implemented: CreateTemplateVersion - createTemplateVersion"))
}

// UpdateTemplateVersionSections is the resolver for the updateTemplateVersionSections field.
func (r *mutationResolver) UpdateTemplateVersionSections(ctx context.Context, id string, sections []*SectionInput) (*TemplateVersion, error) {
	panic(fmt.Errorf("not implemented: UpdateTemplateVersionSections - updateTemplateVersionSections"))
}

// PublishTemplateVersion is the resolver for the publishTemplateVersion field.
func (r *mutationResolver) PublishTemplateVersion(ctx context.Context, id string) (*TemplateVersion, error) {
	panic(fmt.Errorf("not implemented: PublishTemplateVersion - publishTemplateVersion"))
}

// DiscardTemplateVersion is the resolver for the discardTemplateVersion field.
func (r *mutationResolver) DiscardTemplateVersion(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DiscardTemplateVersion - discardTemplateVersion"))
}

// RetireTemplate is the resolver for the retireTemplate field.
func (r *mutationResolver) RetireTemplate(ctx context.Context, id string) (*Template, error) {
	panic(fmt.Errorf("not implemented: RetireTemplate - retireTemplate"))
}

// DeleteTemplate is the resolver for the deleteTemplate field.
func (r *mutationResolver) DeleteTemplate(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTemplate - deleteTemplate"))
}

// RenameTemplate is the resolver for the renameTemplate field.
func (r *mutationResolver) RenameTemplate(ctx context.Context, id string, name string) (*Template, error) {
	panic(fmt.Errorf("not implemented: RenameTemplate - renameTemplate"))
}

// CreatePolicy is the resolver for the createPolicy field.
func (r *mutationResolver) CreatePolicy(ctx context.Context, homeGroupID string, title string, sensitivity Sensitivity, templateID *string, documentType *DocumentType) (*Policy, error) {
	panic(fmt.Errorf("not implemented: CreatePolicy - createPolicy"))
}

// SaveDraft is the resolver for the saveDraft field.
func (r *mutationResolver) SaveDraft(ctx context.Context, policyID string, contentJSON string, templateVersionID *string) (*PolicyVersion, error) {
	panic(fmt.Errorf("not implemented: SaveDraft - saveDraft"))
}

// SetPolicyTemplate is the resolver for the setPolicyTemplate field.
func (r *mutationResolver) SetPolicyTemplate(ctx context.Context, policyID string, templateID *string, none bool) (*Policy, error) {
	panic(fmt.Errorf("not implemented: SetPolicyTemplate - setPolicyTemplate"))
}

// PublishDraft is the resolver for the publishDraft field.
func (r *mutationResolver) PublishDraft(ctx context.Context, policyID string) (*PolicyVersion, error) {
	panic(fmt.Errorf("not implemented: PublishDraft - publishDraft"))
}

// DiscardDraft is the resolver for the discardDraft field.
func (r *mutationResolver) DiscardDraft(ctx context.Context, policyID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DiscardDraft - discardDraft"))
}

// DeletePolicy is the resolver for the deletePolicy field.
func (r *mutationResolver) DeletePolicy(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePolicy - deletePolicy"))
}

// RetirePolicy is the resolver for the retirePolicy field.
func (r *mutationResolver) RetirePolicy(ctx context.Context, id string) (*Policy, error) {
	panic(fmt.Errorf("not implemented: RetirePolicy - retirePolicy"))
}

// SetPolicyOwner is the resolver for the setPolicyOwner field.
func (r *mutationResolver) SetPolicyOwner(ctx context.Context, policyID string, ownerUserID string) (*Policy, error) {
	panic(fmt.Errorf("not implemented: SetPolicyOwner - setPolicyOwner"))
}

// MovePolicy is the resolver for the movePolicy field.
func (r *mutationResolver) MovePolicy(ctx context.Context, policyID string, homeGroupID string) (*Policy, error) {
	panic(fmt.Errorf("not implemented: MovePolicy - movePolicy"))
}

// SetPolicySensitivity is the resolver for the setPolicySensitivity field.
func (r *mutationResolver) SetPolicySensitivity(ctx context.Context, policyID string, sensitivity Sensitivity) (*Policy, error) {
	panic(fmt.Errorf("not implemented: SetPolicySensitivity - setPolicySensitivity"))
}

// RenamePolicy is the resolver for the renamePolicy field.
func (r *mutationResolver) RenamePolicy(ctx context.Context, policyID string, newTitle string) (*RenamePolicyResult, error) {
	panic(fmt.Errorf("not implemented: RenamePolicy - renamePolicy"))
}

// BreakGlassReveal is the resolver for the breakGlassReveal field.
func (r *mutationResolver) BreakGlassReveal(ctx context.Context, policyID string, reason string) (*BreakGlassResult, error) {
	panic(fmt.Errorf("not implemented: BreakGlassReveal - breakGlassReveal"))
}

// ReindexPolicy is the resolver for the reindexPolicy field.
func (r *mutationResolver) ReindexPolicy(ctx context.Context, policyID string) (*ReindexResult, error) {
	panic(fmt.Errorf("not implemented: ReindexPolicy - reindexPolicy"))
}

// ReindexPolicyVersion is the resolver for the reindexPolicyVersion field.
func (r *mutationResolver) ReindexPolicyVersion(ctx context.Context, policyVersionID string) (*ReindexResult, error) {
	panic(fmt.Errorf("not implemented: ReindexPolicyVersion - reindexPolicyVersion"))
}

// SetGroupGovernance is the resolver for the setGroupGovernance field.
func (r *mutationResolver) SetGroupGovernance(ctx context.Context, id string, owners []string, adGroupIds []string, exclusionGroupIds []string, ackTriggers AckTrigger, reviewCadence ReviewCadence, reviewDate *string, ackEveryone *bool) (*Group, error) {
	panic(fmt.Errorf("not implemented: SetGroupGovernance - setGroupGovernance"))
}

// SetPolicyAck is the resolver for the setPolicyAck field.
func (r *mutationResolver) SetPolicyAck(ctx context.Context, policyID string, ackTriggers *AckTrigger, ackAudienceOverride []string) (*Policy, error) {
	panic(fmt.Errorf("not implemented: SetPolicyAck - setPolicyAck"))
}

// SetGlobalSettings is the resolver for the setGlobalSettings field.
func (r *mutationResolver) SetGlobalSettings(ctx context.Context, input GlobalSettingsInput) (*GlobalSettings, error) {
	panic(fmt.Errorf("not implemented: SetGlobalSettings - setGlobalSettings"))
}

// SetMailgunConfig is the resolver for the setMailgunConfig field.
func (r *mutationResolver) SetMailgunConfig(ctx context.Context, input MailgunConfigInput) (*MailgunConfigStatus, error) {
	panic(fmt.Errorf("not implemented: SetMailgunConfig - setMailgunConfig"))
}

// AddAppendix is the resolver for the addAppendix field.
func (r *mutationResolver) AddAppendix(ctx context.Context, policyVersionID string, title string, contentJSON string) (*Appendix, error) {
	panic(fmt.Errorf("not implemented: AddAppendix - addAppendix"))
}

// UpdateAppendix is the resolver for the updateAppendix field.
func (r *mutationResolver) UpdateAppendix(ctx context.Context, id string, title string, contentJSON string) (*Appendix, error) {
	panic(fmt.Errorf("not implemented: UpdateAppendix - updateAppendix"))
}

// ReorderAppendices is the resolver for the reorderAppendices field.
func (r *mutationResolver) ReorderAppendices(ctx context.Context, policyVersionID string, orderedIds []string) ([]*Appendix, error) {
	panic(fmt.Errorf("not implemented: ReorderAppendices - reorderAppendices"))
}

// DeleteAppendix is the resolver for the deleteAppendix field.
func (r *mutationResolver) DeleteAppendix(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAppendix - deleteAppendix"))
}

// SetRelatedPolicies is the resolver for the setRelatedPolicies field.
func (r *mutationResolver) SetRelatedPolicies(ctx context.Context, policyID string, relatedPolicyIds []string) ([]*RelatedPolicy, error) {
	panic(fmt.Errorf("not implemented: SetRelatedPolicies - setRelatedPolicies"))
}

// CreateContactBlock is the resolver for the createContactBlock field.
func (r *mutationResolver) CreateContactBlock(ctx context.Context, block ContactBlockInput) (*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: CreateContactBlock - createContactBlock"))
}

// UpdateContactBlock is the resolver for the updateContactBlock field.
func (r *mutationResolver) UpdateContactBlock(ctx context.Context, id string, block ContactBlockInput) (*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: UpdateContactBlock - updateContactBlock"))
}

// DeleteContactBlock is the resolver for the deleteContactBlock field.
func (r *mutationResolver) DeleteContactBlock(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteContactBlock - deleteContactBlock"))
}

// SetContactBlockArchived is the resolver for the setContactBlockArchived field.
func (r *mutationResolver) SetContactBlockArchived(ctx context.Context, id string, archived bool) (*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: SetContactBlockArchived - setContactBlockArchived"))
}

// SetPolicyContactBlocks is the resolver for the setPolicyContactBlocks field.
func (r *mutationResolver) SetPolicyContactBlocks(ctx context.Context, policyID string, contactBlockIds []string) ([]*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: SetPolicyContactBlocks - setPolicyContactBlocks"))
}

// CreateReference is the resolver for the createReference field.
func (r *mutationResolver) CreateReference(ctx context.Context, input ReferenceInput) (*Reference, error) {
	panic(fmt.Errorf("not implemented: CreateReference - createReference"))
}

// UpdateReference is the resolver for the updateReference field.
func (r *mutationResolver) UpdateReference(ctx context.Context, id string, input ReferenceInput) (*Reference, error) {
	panic(fmt.Errorf("not implemented: UpdateReference - updateReference"))
}

// DeleteReference is the resolver for the deleteReference field.
func (r *mutationResolver) DeleteReference(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteReference - deleteReference"))
}

// SetReferenceArchived is the resolver for the setReferenceArchived field.
func (r *mutationResolver) SetReferenceArchived(ctx context.Context, id string, archived bool) (*Reference, error) {
	panic(fmt.Errorf("not implemented: SetReferenceArchived - setReferenceArchived"))
}

// SetPolicyReferences is the resolver for the setPolicyReferences field.
func (r *mutationResolver) SetPolicyReferences(ctx context.Context, policyID string, referenceIds []string) ([]*Reference, error) {
	panic(fmt.Errorf("not implemented: SetPolicyReferences - setPolicyReferences"))
}

// CreateDefinition is the resolver for the createDefinition field.
func (r *mutationResolver) CreateDefinition(ctx context.Context, input DefinitionEntryInput) (*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: CreateDefinition - createDefinition"))
}

// UpdateDefinition is the resolver for the updateDefinition field.
func (r *mutationResolver) UpdateDefinition(ctx context.Context, id string, input DefinitionEntryInput) (*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: UpdateDefinition - updateDefinition"))
}

// DeleteDefinition is the resolver for the deleteDefinition field.
func (r *mutationResolver) DeleteDefinition(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDefinition - deleteDefinition"))
}

// SetDefinitionArchived is the resolver for the setDefinitionArchived field.
func (r *mutationResolver) SetDefinitionArchived(ctx context.Context, id string, archived bool) (*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: SetDefinitionArchived - setDefinitionArchived"))
}

// SetPolicyDefinitionEntries is the resolver for the setPolicyDefinitionEntries field.
func (r *mutationResolver) SetPolicyDefinitionEntries(ctx context.Context, policyID string, definitionIds []string) ([]*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: SetPolicyDefinitionEntries - setPolicyDefinitionEntries"))
}

// SetCategoryRuleset is the resolver for the setCategoryRuleset field.
func (r *mutationResolver) SetCategoryRuleset(ctx context.Context, categoryID string, rules []*RaciRuleInput) (*CategoryRuleset, error) {
	panic(fmt.Errorf("not implemented: SetCategoryRuleset - setCategoryRuleset"))
}

// Appendices is the resolver for the appendices field.
func (r *policyVersionResolver) Appendices(ctx context.Context, obj *PolicyVersion) ([]*Appendix, error) {
	panic(fmt.Errorf("not implemented: Appendices - appendices"))
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*Group, error) {
	panic(fmt.Errorf("not implemented: Group - group"))
}

// GroupChildren is the resolver for the groupChildren field.
func (r *queryResolver) GroupChildren(ctx context.Context, parentID *string) ([]*Group, error) {
	panic(fmt.Errorf("not implemented: GroupChildren - groupChildren"))
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, ownerGroupID *string) ([]*Template, error) {
	panic(fmt.Errorf("not implemented: Templates - templates"))
}

// LatestTemplateVersion is the resolver for the latestTemplateVersion field.
func (r *queryResolver) LatestTemplateVersion(ctx context.Context, templateID string) (*TemplateVersion, error) {
	panic(fmt.Errorf("not implemented: LatestTemplateVersion - latestTemplateVersion"))
}

// TemplateVersions is the resolver for the templateVersions field.
func (r *queryResolver) TemplateVersions(ctx context.Context, templateID string) ([]*TemplateVersion, error) {
	panic(fmt.Errorf("not implemented: TemplateVersions - templateVersions"))
}

// Policy is the resolver for the policy field.
func (r *queryResolver) Policy(ctx context.Context, id string) (*Policy, error) {
	panic(fmt.Errorf("not implemented: Policy - policy"))
}

// Policies is the resolver for the policies field.
func (r *queryResolver) Policies(ctx context.Context, groupID string, includeDescendants *bool, documentType *DocumentType) ([]*Policy, error) {
	panic(fmt.Errorf("not implemented: Policies - policies"))
}

// PolicyVersion is the resolver for the policyVersion field.
func (r *queryResolver) PolicyVersion(ctx context.Context, id string) (*PolicyVersion, error) {
	panic(fmt.Errorf("not implemented: PolicyVersion - policyVersion"))
}

// PolicyVersions is the resolver for the policyVersions field.
func (r *queryResolver) PolicyVersions(ctx context.Context, policyID string) ([]*PolicyVersion, error) {
	panic(fmt.Errorf("not implemented: PolicyVersions - policyVersions"))
}

// DiffVersions is the resolver for the diffVersions field.
func (r *queryResolver) DiffVersions(ctx context.Context, fromVersionID string, toVersionID string) ([]*SectionDiff, error) {
	panic(fmt.Errorf("not implemented: DiffVersions - diffVersions"))
}

// EffectiveTemplate is the resolver for the effectiveTemplate field.
func (r *queryResolver) EffectiveTemplate(ctx context.Context, policyID string) (*EffectiveTemplate, error) {
	panic(fmt.Errorf("not implemented: EffectiveTemplate - effectiveTemplate"))
}

// EffectiveGovernance is the resolver for the effectiveGovernance field.
func (r *queryResolver) EffectiveGovernance(ctx context.Context, groupID string) (*EffectiveGovernance, error) {
	panic(fmt.Errorf("not implemented: EffectiveGovernance - effectiveGovernance"))
}

// GlobalSettings is the resolver for the globalSettings field.
func (r *queryResolver) GlobalSettings(ctx context.Context) (*GlobalSettings, error) {
	panic(fmt.Errorf("not implemented: GlobalSettings - globalSettings"))
}

// MailgunConfig is the resolver for the mailgunConfig field.
func (r *queryResolver) MailgunConfig(ctx context.Context) (*MailgunConfigStatus, error) {
	panic(fmt.Errorf("not implemented: MailgunConfig - mailgunConfig"))
}

// RelatedPolicies is the resolver for the relatedPolicies field.
func (r *queryResolver) RelatedPolicies(ctx context.Context, policyID string) ([]*RelatedPolicy, error) {
	panic(fmt.Errorf("not implemented: RelatedPolicies - relatedPolicies"))
}

// RelatedPolicyCandidates is the resolver for the relatedPolicyCandidates field.
func (r *queryResolver) RelatedPolicyCandidates(ctx context.Context, policyID string) ([]*Policy, error) {
	panic(fmt.Errorf("not implemented: RelatedPolicyCandidates - relatedPolicyCandidates"))
}

// ContactBlocks is the resolver for the contactBlocks field.
func (r *queryResolver) ContactBlocks(ctx context.Context, includeArchived *bool) ([]*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: ContactBlocks - contactBlocks"))
}

// PolicyContactBlocks is the resolver for the policyContactBlocks field.
func (r *queryResolver) PolicyContactBlocks(ctx context.Context, policyID string) ([]*ContactBlock, error) {
	panic(fmt.Errorf("not implemented: PolicyContactBlocks - policyContactBlocks"))
}

// References is the resolver for the references field.
func (r *queryResolver) References(ctx context.Context, includeArchived *bool) ([]*Reference, error) {
	panic(fmt.Errorf("not implemented: References - references"))
}

// PolicyReferences is the resolver for the policyReferences field.
func (r *queryResolver) PolicyReferences(ctx context.Context, policyID string) ([]*Reference, error) {
	panic(fmt.Errorf("not implemented: PolicyReferences - policyReferences"))
}

// Definitions is the resolver for the definitions field.
func (r *queryResolver) Definitions(ctx context.Context, categoryID *string, includeArchived *bool) ([]*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: Definitions - definitions"))
}

// PolicyDefinitionCandidates is the resolver for the policyDefinitionCandidates field.
func (r *queryResolver) PolicyDefinitionCandidates(ctx context.Context, policyID string, includeArchived *bool) ([]*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: PolicyDefinitionCandidates - policyDefinitionCandidates"))
}

// PolicyDefinitionEntries is the resolver for the policyDefinitionEntries field.
func (r *queryResolver) PolicyDefinitionEntries(ctx context.Context, policyID string) ([]*DefinitionEntry, error) {
	panic(fmt.Errorf("not implemented: PolicyDefinitionEntries - policyDefinitionEntries"))
}

// CategoryRuleset is the resolver for the categoryRuleset field.
func (r *queryResolver) CategoryRuleset(ctx context.Context, categoryID string) (*CategoryRuleset, error) {
	panic(fmt.Errorf("not implemented: CategoryRuleset - categoryRuleset"))
}

// SimulateCategory is the resolver for the simulateCategory field.
func (r *queryResolver) SimulateCategory(ctx context.Context, categoryID string, userID string, draftRules []*RaciRuleInput) (*RaciDecision, error) {
	panic(fmt.Errorf("not implemented: SimulateCategory - simulateCategory"))
}

// CategoryApprovers is the resolver for the categoryApprovers field.
func (r *queryResolver) CategoryApprovers(ctx context.Context, categoryID string) ([]*User, error) {
	panic(fmt.Errorf("not implemented: CategoryApprovers - categoryApprovers"))
}

// ViewerIsApprover is the resolver for the viewerIsApprover field.
func (r *queryResolver) ViewerIsApprover(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: ViewerIsApprover - viewerIsApprover"))
}

// PolicyVersion returns PolicyVersionResolver implementation.
func (r *Resolver) PolicyVersion() PolicyVersionResolver { return &policyVersionResolver{r} }

type policyVersionResolver struct{ *Resolver }
