// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// RequestPDFExport is the resolver for the requestPDFExport field.
func (r *mutationResolver) RequestPDFExport(ctx context.Context, policyVersionID string) (*PDFExportJob, error) {
	return RequestPDFExport(ctx, r.DeliveryClient, policyVersionID)
}

// CreateMagicLink is the resolver for the createMagicLink field.
func (r *mutationResolver) CreateMagicLink(ctx context.Context, policyVersionID string, sensitive bool) (*MagicLink, error) {
	return CreateMagicLinkResolver(ctx, r.DeliveryClient, policyVersionID, sensitive)
}

// RevokeMagicLink is the resolver for the revokeMagicLink field.
func (r *mutationResolver) RevokeMagicLink(ctx context.Context, token string) (bool, error) {
	return RevokeMagicLinkResolver(ctx, r.DeliveryClient, token)
}

// RenderedContent is the resolver for the renderedContent field.
func (r *queryResolver) RenderedContent(ctx context.Context, policyVersionID string) (*RenderedContent, error) {
	return GetRenderedContent(ctx, r.DeliveryClient, policyVersionID)
}

// PolicyDiff is the resolver for the policyDiff field.
func (r *queryResolver) PolicyDiff(ctx context.Context, fromVersionID string, toVersionID string) (*PolicyDiff, error) {
	return GetPolicyDiff(ctx, r.DeliveryClient, fromVersionID, toVersionID)
}

// PDFDownloadLink is the resolver for the pdfDownloadLink field.
func (r *queryResolver) PDFDownloadLink(ctx context.Context, jobID string) (*PDFDownloadLink, error) {
	return GetPDFDownloadLink(ctx, r.DeliveryClient, jobID)
}
