// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// GrantRole is the resolver for the grantRole field.
func (r *mutationResolver) GrantRole(ctx context.Context, userID string, role string, category *string) (*User, error) {
	panic(fmt.Errorf("not implemented: GrantRole - grantRole"))
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, role string, category *string) (*User, error) {
	panic(fmt.Errorf("not implemented: RevokeRole - revokeRole"))
}

// EnableUser is the resolver for the enableUser field.
func (r *mutationResolver) EnableUser(ctx context.Context, userID string) (*User, error) {
	panic(fmt.Errorf("not implemented: EnableUser - enableUser"))
}

// DisableUser is the resolver for the disableUser field.
func (r *mutationResolver) DisableUser(ctx context.Context, userID string) (*User, error) {
	panic(fmt.Errorf("not implemented: DisableUser - disableUser"))
}

// ReassignUserPolicies is the resolver for the reassignUserPolicies field.
func (r *mutationResolver) ReassignUserPolicies(ctx context.Context, fromUserID string, toUserID string) (*ReassignUserPoliciesResult, error) {
	panic(fmt.Errorf("not implemented: ReassignUserPolicies - reassignUserPolicies"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*DeleteUserResult, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// MergeAccounts is the resolver for the mergeAccounts field.
func (r *mutationResolver) MergeAccounts(ctx context.Context, sourceUserID string, targetUserID string, confirmPrivileged *bool, idempotencyKey *string) (*MergeAccountsResult, error) {
	panic(fmt.Errorf("not implemented: MergeAccounts - mergeAccounts"))
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID string, groupID string) (*User, error) {
	panic(fmt.Errorf("not implemented: AddUserToGroup - addUserToGroup"))
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID string, groupID string) (*User, error) {
	panic(fmt.Errorf("not implemented: RemoveUserFromGroup - removeUserFromGroup"))
}

// GrantGroupManager is the resolver for the grantGroupManager field.
func (r *mutationResolver) GrantGroupManager(ctx context.Context, userID string, groupID string) (*User, error) {
	panic(fmt.Errorf("not implemented: GrantGroupManager - grantGroupManager"))
}

// RevokeGroupManager is the resolver for the revokeGroupManager field.
func (r *mutationResolver) RevokeGroupManager(ctx context.Context, userID string, groupID string) (*User, error) {
	panic(fmt.Errorf("not implemented: RevokeGroupManager - revokeGroupManager"))
}

// SetUserPolicyOverride is the resolver for the setUserPolicyOverride field.
func (r *mutationResolver) SetUserPolicyOverride(ctx context.Context, userID string, policyNumber string, effect *OverrideEffect) (*User, error) {
	panic(fmt.Errorf("not implemented: SetUserPolicyOverride - setUserPolicyOverride"))
}

// RequestStepUpOtp is the resolver for the requestStepUpOtp field.
func (r *mutationResolver) RequestStepUpOtp(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestStepUpOtp - requestStepUpOtp"))
}

// TransferRoot is the resolver for the transferRoot field.
func (r *mutationResolver) TransferRoot(ctx context.Context, toUserID string, otp string) (*User, error) {
	panic(fmt.Errorf("not implemented: TransferRoot - transferRoot"))
}

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, acceptTerms bool, username *string, firstName *string, lastName *string, email *string) (*User, error) {
	panic(fmt.Errorf("not implemented: CompleteOnboarding - completeOnboarding"))
}

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationResolver) UpdateMyProfile(ctx context.Context, firstName *string, lastName *string, locale *string) (*User, error) {
	panic(fmt.Errorf("not implemented: UpdateMyProfile - updateMyProfile"))
}

// RevokeUserSessions is the resolver for the revokeUserSessions field.
func (r *mutationResolver) RevokeUserSessions(ctx context.Context, userID string, reason *string) (int, error) {
	panic(fmt.Errorf("not implemented: RevokeUserSessions - revokeUserSessions"))
}

// RevokeMySessions is the resolver for the revokeMySessions field.
func (r *mutationResolver) RevokeMySessions(ctx context.Context) (int, error) {
	panic(fmt.Errorf("not implemented: RevokeMySessions - revokeMySessions"))
}

// CreateLocalUser is the resolver for the createLocalUser field.
func (r *mutationResolver) CreateLocalUser(ctx context.Context, username string, email string, name string, password string) (*User, error) {
	panic(fmt.Errorf("not implemented: CreateLocalUser - createLocalUser"))
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, userID string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: ResetUserPassword - resetUserPassword"))
}

// ResendWelcomeEmail is the resolver for the resendWelcomeEmail field.
func (r *mutationResolver) ResendWelcomeEmail(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: ResendWelcomeEmail - resendWelcomeEmail"))
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, userID string, name string, email string) (*User, error) {
	panic(fmt.Errorf("not implemented: UpdateUserProfile - updateUserProfile"))
}

// CreateDirectoryGroup is the resolver for the createDirectoryGroup field.
func (r *mutationResolver) CreateDirectoryGroup(ctx context.Context, name string) (*DirectoryGroup, error) {
	panic(fmt.Errorf("not implemented: CreateDirectoryGroup - createDirectoryGroup"))
}

// RenameDirectoryGroup is the resolver for the renameDirectoryGroup field.
func (r *mutationResolver) RenameDirectoryGroup(ctx context.Context, groupID int, name string) (*DirectoryGroup, error) {
	panic(fmt.Errorf("not implemented: RenameDirectoryGroup - renameDirectoryGroup"))
}

// DeleteDirectoryGroup is the resolver for the deleteDirectoryGroup field.
func (r *mutationResolver) DeleteDirectoryGroup(ctx context.Context, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDirectoryGroup - deleteDirectoryGroup"))
}

// AddUserToDirectoryGroup is the resolver for the addUserToDirectoryGroup field.
func (r *mutationResolver) AddUserToDirectoryGroup(ctx context.Context, userID string, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: AddUserToDirectoryGroup - addUserToDirectoryGroup"))
}

// RemoveUserFromDirectoryGroup is the resolver for the removeUserFromDirectoryGroup field.
func (r *mutationResolver) RemoveUserFromDirectoryGroup(ctx context.Context, userID string, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveUserFromDirectoryGroup - removeUserFromDirectoryGroup"))
}

// EnrollTotpBegin is the resolver for the enrollTotpBegin field.
func (r *mutationResolver) EnrollTotpBegin(ctx context.Context) (*TotpEnrollment, error) {
	panic(fmt.Errorf("not implemented: EnrollTotpBegin - enrollTotpBegin"))
}

// EnrollTotpConfirm is the resolver for the enrollTotpConfirm field.
func (r *mutationResolver) EnrollTotpConfirm(ctx context.Context, code string) (bool, error) {
	panic(fmt.Errorf("not implemented: EnrollTotpConfirm - enrollTotpConfirm"))
}

// SendEnrollEmailOtp is the resolver for the sendEnrollEmailOtp field.
func (r *mutationResolver) SendEnrollEmailOtp(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: SendEnrollEmailOtp - sendEnrollEmailOtp"))
}

// VerifyEnrollEmailOtp is the resolver for the verifyEnrollEmailOtp field.
func (r *mutationResolver) VerifyEnrollEmailOtp(ctx context.Context, code string) (bool, error) {
	panic(fmt.Errorf("not implemented: VerifyEnrollEmailOtp - verifyEnrollEmailOtp"))
}

// WebauthnRegisterBegin is the resolver for the webauthnRegisterBegin field.
func (r *mutationResolver) WebauthnRegisterBegin(ctx context.Context) (*WebauthnRegistration, error) {
	panic(fmt.Errorf("not implemented: WebauthnRegisterBegin - webauthnRegisterBegin"))
}

// WebauthnRegisterFinish is the resolver for the webauthnRegisterFinish field.
func (r *mutationResolver) WebauthnRegisterFinish(ctx context.Context, sessionID string, credentialJSON string, label *string) (bool, error) {
	panic(fmt.Errorf("not implemented: WebauthnRegisterFinish - webauthnRegisterFinish"))
}

// RemoveFactor is the resolver for the removeFactor field.
func (r *mutationResolver) RemoveFactor(ctx context.Context, kind string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveFactor - removeFactor"))
}

// RemoveWebauthnCredential is the resolver for the removeWebauthnCredential field.
func (r *mutationResolver) RemoveWebauthnCredential(ctx context.Context, credentialID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveWebauthnCredential - removeWebauthnCredential"))
}

// RenameMfaMethod is the resolver for the renameMfaMethod field.
func (r *mutationResolver) RenameMfaMethod(ctx context.Context, methodID string, label string) (bool, error) {
	panic(fmt.Errorf("not implemented: RenameMfaMethod - renameMfaMethod"))
}

// RemoveUserMfaFactor is the resolver for the removeUserMfaFactor field.
func (r *mutationResolver) RemoveUserMfaFactor(ctx context.Context, userID string, methodID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveUserMfaFactor - removeUserMfaFactor"))
}

// RenameUserMfaFactor is the resolver for the renameUserMfaFactor field.
func (r *mutationResolver) RenameUserMfaFactor(ctx context.Context, userID string, methodID string, label string) (bool, error) {
	panic(fmt.Errorf("not implemented: RenameUserMfaFactor - renameUserMfaFactor"))
}

// StartImpersonation is the resolver for the startImpersonation field.
func (r *mutationResolver) StartImpersonation(ctx context.Context, userID string, reason string) (*ImpersonationSession, error) {
	panic(fmt.Errorf("not implemented: StartImpersonation - startImpersonation"))
}

// StopImpersonation is the resolver for the stopImpersonation field.
func (r *mutationResolver) StopImpersonation(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: StopImpersonation - stopImpersonation"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, pageSize *int, pageToken *string, includeDeleted *bool) (*UserPage, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// ResolveUserLabels is the resolver for the resolveUserLabels field.
func (r *queryResolver) ResolveUserLabels(ctx context.Context, ids []string) ([]*UserLabel, error) {
	panic(fmt.Errorf("not implemented: ResolveUserLabels - resolveUserLabels"))
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, limit *int) ([]*UserLabel, error) {
	panic(fmt.Errorf("not implemented: SearchUsers - searchUsers"))
}

// PoliciesByOwner is the resolver for the policiesByOwner field.
func (r *queryResolver) PoliciesByOwner(ctx context.Context, userID string, includeRetired *bool) ([]*Policy, error) {
	panic(fmt.Errorf("not implemented: PoliciesByOwner - policiesByOwner"))
}

// PreviewAccountMerge is the resolver for the previewAccountMerge field.
func (r *queryResolver) PreviewAccountMerge(ctx context.Context, sourceUserID string, targetUserID string) (*AccountMergePreview, error) {
	panic(fmt.Errorf("not implemented: PreviewAccountMerge - previewAccountMerge"))
}

// PreviewUserDeletion is the resolver for the previewUserDeletion field.
func (r *queryResolver) PreviewUserDeletion(ctx context.Context, userID string) (*UserDeletionPreview, error) {
	panic(fmt.Errorf("not implemented: PreviewUserDeletion - previewUserDeletion"))
}

// ManagedGroupMembers is the resolver for the managedGroupMembers field.
func (r *queryResolver) ManagedGroupMembers(ctx context.Context, groupID string) ([]*User, error) {
	panic(fmt.Errorf("not implemented: ManagedGroupMembers - managedGroupMembers"))
}

// ListUserSessions is the resolver for the listUserSessions field.
func (r *queryResolver) ListUserSessions(ctx context.Context, userID string) ([]*Session, error) {
	panic(fmt.Errorf("not implemented: ListUserSessions - listUserSessions"))
}

// DirectoryGroups is the resolver for the directoryGroups field.
func (r *queryResolver) DirectoryGroups(ctx context.Context) ([]*DirectoryGroup, error) {
	panic(fmt.Errorf("not implemented: DirectoryGroups - directoryGroups"))
}

// GroupMembers is the resolver for the groupMembers field.
func (r *queryResolver) GroupMembers(ctx context.Context, groupID int) ([]*DirectoryMember, error) {
	panic(fmt.Errorf("not implemented: GroupMembers - groupMembers"))
}

// MyFactors is the resolver for the myFactors field.
func (r *queryResolver) MyFactors(ctx context.Context) ([]*UserFactor, error) {
	panic(fmt.Errorf("not implemented: MyFactors - myFactors"))
}

// MyWebauthnCredentials is the resolver for the myWebauthnCredentials field.
func (r *queryResolver) MyWebauthnCredentials(ctx context.Context) ([]*WebauthnCredentialInfo, error) {
	panic(fmt.Errorf("not implemented: MyWebauthnCredentials - myWebauthnCredentials"))
}

// UserFactors is the resolver for the userFactors field.
func (r *queryResolver) UserFactors(ctx context.Context, userID string) ([]*MfaFactor, error) {
	panic(fmt.Errorf("not implemented: UserFactors - userFactors"))
}

// ImpersonationStatus is the resolver for the impersonationStatus field.
func (r *queryResolver) ImpersonationStatus(ctx context.Context) (*ImpersonationSession, error) {
	panic(fmt.Errorf("not implemented: ImpersonationStatus - impersonationStatus"))
}
