// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/Steward-GRC/steward-gateway/internal/bff"
)

// GrantRole is the resolver for the grantRole field.
func (r *mutationResolver) GrantRole(ctx context.Context, userID string, role string, category *string) (*User, error) {
	return GrantRoleResolver(ctx, r.IdentityAdminClient, userID, role, category)
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, role string, category *string) (*User, error) {
	return RevokeRoleResolver(ctx, r.IdentityAdminClient, userID, role, category)
}

// EnableUser is the resolver for the enableUser field.
func (r *mutationResolver) EnableUser(ctx context.Context, userID string) (*User, error) {
	return EnableUserResolver(ctx, r.IdentityAdminClient, userID)
}

// DisableUser is the resolver for the disableUser field.
func (r *mutationResolver) DisableUser(ctx context.Context, userID string) (*User, error) {
	return DisableUserResolver(ctx, r.IdentityAdminClient, userID)
}

// ReassignUserPolicies is the resolver for the reassignUserPolicies field.
func (r *mutationResolver) ReassignUserPolicies(ctx context.Context, fromUserID string, toUserID string) (*ReassignUserPoliciesResult, error) {
	return ReassignUserPolicies(ctx, r.PolicyClient, fromUserID, toUserID)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*DeleteUserResult, error) {
	return DeleteUserResolver(ctx, r.PolicyClient, r.IdentityAdminClient, userID)
}

// MergeAccounts is the resolver for the mergeAccounts field.
func (r *mutationResolver) MergeAccounts(ctx context.Context, sourceUserID string, targetUserID string, confirmPrivileged *bool, idempotencyKey *string) (*MergeAccountsResult, error) {
	return MergeAccountsResolver(ctx, r.IdentityAdminClient, sourceUserID, targetUserID, confirmPrivileged, idempotencyKey)
}

// CreatePlatformGroup is the resolver for the createPlatformGroup field.
func (r *mutationResolver) CreatePlatformGroup(ctx context.Context, name string, parentID *string) (*PlatformGroup, error) {
	return CreatePlatformGroupResolver(ctx, r.IdentityAdminClient, name, parentID)
}

// AddUserToGroup is the resolver for the addUserToGroup field.
func (r *mutationResolver) AddUserToGroup(ctx context.Context, userID string, groupID string) (*User, error) {
	return AddUserToGroupResolver(ctx, r.IdentityAdminClient, r.IdentityClient, userID, groupID)
}

// RemoveUserFromGroup is the resolver for the removeUserFromGroup field.
func (r *mutationResolver) RemoveUserFromGroup(ctx context.Context, userID string, groupID string) (*User, error) {
	return RemoveUserFromGroupResolver(ctx, r.IdentityAdminClient, r.IdentityClient, userID, groupID)
}

// GrantGroupManager is the resolver for the grantGroupManager field.
func (r *mutationResolver) GrantGroupManager(ctx context.Context, userID string, groupID string) (*User, error) {
	return GrantGroupManagerResolver(ctx, r.IdentityAdminClient, userID, groupID)
}

// RevokeGroupManager is the resolver for the revokeGroupManager field.
func (r *mutationResolver) RevokeGroupManager(ctx context.Context, userID string, groupID string) (*User, error) {
	return RevokeGroupManagerResolver(ctx, r.IdentityAdminClient, userID, groupID)
}

// SetUserPolicyOverride is the resolver for the setUserPolicyOverride field.
func (r *mutationResolver) SetUserPolicyOverride(ctx context.Context, userID string, policyNumber string, effect *OverrideEffect) (*User, error) {
	return SetUserPolicyOverrideResolver(ctx, r.IdentityAdminClient, userID, policyNumber, effect)
}

// RequestStepUpOtp is the resolver for the requestStepUpOtp field.
func (r *mutationResolver) RequestStepUpOtp(ctx context.Context) (bool, error) {
	return RequestStepUpOtpResolver(ctx, r.IdentityAdminClient)
}

// GrantRoot is the resolver for the grantRoot field.
func (r *mutationResolver) GrantRoot(ctx context.Context, userID string, otp string) (*User, error) {
	return GrantRootResolver(ctx, r.IdentityAdminClient, userID, otp)
}

// RevokeRoot is the resolver for the revokeRoot field.
func (r *mutationResolver) RevokeRoot(ctx context.Context, userID string, otp string) (*User, error) {
	return RevokeRootResolver(ctx, r.IdentityAdminClient, userID, otp)
}

// RequestHardReset is the resolver for the requestHardReset field.
func (r *mutationResolver) RequestHardReset(ctx context.Context, module string, reason string) (*HardResetRequest, error) {
	return RequestHardResetResolver(ctx, r.IdentityAdminClient, module, reason)
}

// ApproveHardReset is the resolver for the approveHardReset field.
func (r *mutationResolver) ApproveHardReset(ctx context.Context, requestID string) (*HardResetRequest, error) {
	return ApproveHardResetResolver(ctx, r.IdentityAdminClient, requestID)
}

// CancelHardReset is the resolver for the cancelHardReset field.
func (r *mutationResolver) CancelHardReset(ctx context.Context, requestID string) (*HardResetRequest, error) {
	return CancelHardResetResolver(ctx, r.IdentityAdminClient, requestID)
}

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, acceptTerms bool, username *string, firstName *string, lastName *string, email *string) (*User, error) {
	return CompleteOnboardingResolver(ctx, r.IdentityAdminClient, acceptTerms, username, firstName, lastName, email)
}

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationResolver) UpdateMyProfile(ctx context.Context, firstName *string, lastName *string, locale *string) (*User, error) {
	return UpdateMyProfileResolver(ctx, r.IdentityAdminClient, firstName, lastName, locale)
}

// RevokeUserSessions is the resolver for the revokeUserSessions field.
func (r *mutationResolver) RevokeUserSessions(ctx context.Context, userID string, reason *string) (int, error) {
	return RevokeUserSessionsResolver(ctx, r.IdentityAdminClient, userID, reason)
}

// RevokeMySessions is the resolver for the revokeMySessions field.
func (r *mutationResolver) RevokeMySessions(ctx context.Context) (int, error) {
	return RevokeMySessionsResolver(ctx, r.IdentityClient)
}

// CreateLocalUser is the resolver for the createLocalUser field.
func (r *mutationResolver) CreateLocalUser(ctx context.Context, username string, email string, name string, password string) (*User, error) {
	return CreateLocalUserResolver(ctx, r.IdentityAdminClient, username, email, name, password)
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, userID string, newPassword string) (bool, error) {
	return ResetUserPasswordResolver(ctx, r.IdentityAdminClient, userID, newPassword)
}

// ResendWelcomeEmail is the resolver for the resendWelcomeEmail field.
func (r *mutationResolver) ResendWelcomeEmail(ctx context.Context, userID string) (bool, error) {
	return ResendWelcomeEmailResolver(ctx, r.WelcomeClient, userID)
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, userID string, name string, email string) (*User, error) {
	return UpdateUserProfileResolver(ctx, r.IdentityAdminClient, userID, name, email)
}

// EnrollTotpBegin is the resolver for the enrollTotpBegin field.
func (r *mutationResolver) EnrollTotpBegin(ctx context.Context) (*TotpEnrollment, error) {
	return EnrollTotpBeginResolver(ctx, r.IdentityClient)
}

// EnrollTotpConfirm is the resolver for the enrollTotpConfirm field.
func (r *mutationResolver) EnrollTotpConfirm(ctx context.Context, code string) (bool, error) {
	return EnrollTotpConfirmResolver(ctx, r.IdentityClient, code)
}

// SendEnrollEmailOtp is the resolver for the sendEnrollEmailOtp field.
func (r *mutationResolver) SendEnrollEmailOtp(ctx context.Context) (bool, error) {
	return SendEnrollEmailOtpResolver(ctx, r.IdentityClient)
}

// VerifyEnrollEmailOtp is the resolver for the verifyEnrollEmailOtp field.
func (r *mutationResolver) VerifyEnrollEmailOtp(ctx context.Context, code string) (bool, error) {
	return VerifyEnrollEmailOtpResolver(ctx, r.IdentityClient, code)
}

// WebauthnRegisterBegin is the resolver for the webauthnRegisterBegin field.
func (r *mutationResolver) WebauthnRegisterBegin(ctx context.Context) (*WebauthnRegistration, error) {
	return WebauthnRegisterBeginResolver(ctx, r.IdentityClient)
}

// WebauthnRegisterFinish is the resolver for the webauthnRegisterFinish field.
func (r *mutationResolver) WebauthnRegisterFinish(ctx context.Context, sessionID string, credentialJSON string, label *string) (bool, error) {
	return WebauthnRegisterFinishResolver(ctx, r.IdentityClient, sessionID, credentialJSON, label)
}

// RemoveFactor is the resolver for the removeFactor field.
func (r *mutationResolver) RemoveFactor(ctx context.Context, kind string) (bool, error) {
	return RemoveFactorResolver(ctx, r.IdentityClient, kind)
}

// RemoveWebauthnCredential is the resolver for the removeWebauthnCredential field.
func (r *mutationResolver) RemoveWebauthnCredential(ctx context.Context, credentialID string) (bool, error) {
	return RemoveWebauthnCredentialResolver(ctx, r.IdentityClient, credentialID)
}

// RenameMfaMethod is the resolver for the renameMfaMethod field.
func (r *mutationResolver) RenameMfaMethod(ctx context.Context, methodID string, label string) (bool, error) {
	return RenameMfaMethodResolver(ctx, r.IdentityClient, methodID, label)
}

// RemoveUserMfaFactor is the resolver for the removeUserMfaFactor field.
func (r *mutationResolver) RemoveUserMfaFactor(ctx context.Context, userID string, methodID string) (bool, error) {
	return RemoveUserMfaFactorResolver(ctx, r.IdentityAdminClient, userID, methodID)
}

// RenameUserMfaFactor is the resolver for the renameUserMfaFactor field.
func (r *mutationResolver) RenameUserMfaFactor(ctx context.Context, userID string, methodID string, label string) (bool, error) {
	return RenameUserMfaFactorResolver(ctx, r.IdentityAdminClient, userID, methodID, label)
}

// StartImpersonation is the resolver for the startImpersonation field.
func (r *mutationResolver) StartImpersonation(ctx context.Context, userID string, reason string) (*ImpersonationSession, error) {
	sid, _ := bff.SessionIDFromContext(ctx)
	return StartImpersonationResolver(ctx, r.SessionStore, sid, r.IdentityClient, r.AuditEmitter, time.Now, userID, reason)
}

// StopImpersonation is the resolver for the stopImpersonation field.
func (r *mutationResolver) StopImpersonation(ctx context.Context) (bool, error) {
	sid, _ := bff.SessionIDFromContext(ctx)
	return StopImpersonationResolver(ctx, r.SessionStore, sid, r.AuditEmitter)
}

// HardResetRequests is the resolver for the hardResetRequests field.
func (r *queryResolver) HardResetRequests(ctx context.Context, module *string) ([]*HardResetRequest, error) {
	return HardResetRequestsResolver(ctx, r.IdentityAdminClient, module)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	return MeResolver(ctx, r.IdentityClient, r.CategoryClient)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, pageSize *int, pageToken *string, includeDeleted *bool) (*UserPage, error) {
	return UsersResolver(ctx, r.IdentityClient, search, pageSize, pageToken, includeDeleted)
}

// ResolveUserLabels is the resolver for the resolveUserLabels field.
func (r *queryResolver) ResolveUserLabels(ctx context.Context, ids []string) ([]*UserLabel, error) {
	return ResolveUserLabelsResolver(ctx, r.IdentityClient, ids)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, limit *int) ([]*UserLabel, error) {
	return SearchUsersResolver(ctx, r.IdentityClient, query, limit)
}

// PoliciesByOwner is the resolver for the policiesByOwner field.
func (r *queryResolver) PoliciesByOwner(ctx context.Context, userID string, includeRetired *bool) ([]*Policy, error) {
	return ListPoliciesByOwner(ctx, r.PolicyClient, userID, includeRetired)
}

// MyDrafts is the resolver for the myDrafts field.
func (r *queryResolver) MyDrafts(ctx context.Context) ([]*Policy, error) {
	return MyDrafts(ctx, r.PolicyClient, r.CategoryClient, r.IdentityAdminClient, r.IdentityClient)
}

// PreviewAccountMerge is the resolver for the previewAccountMerge field.
func (r *queryResolver) PreviewAccountMerge(ctx context.Context, sourceUserID string, targetUserID string) (*AccountMergePreview, error) {
	return PreviewAccountMergeResolver(ctx, r.IdentityAdminClient, sourceUserID, targetUserID)
}

// PreviewUserDeletion is the resolver for the previewUserDeletion field.
func (r *queryResolver) PreviewUserDeletion(ctx context.Context, userID string) (*UserDeletionPreview, error) {
	return PreviewUserDeletionResolver(ctx, r.IdentityAdminClient, userID)
}

// ManagedGroupMembers is the resolver for the managedGroupMembers field.
func (r *queryResolver) ManagedGroupMembers(ctx context.Context, groupID string) ([]*User, error) {
	return ManagedGroupMembersResolver(ctx, r.IdentityClient, groupID)
}

// PlatformGroups is the resolver for the platformGroups field.
func (r *queryResolver) PlatformGroups(ctx context.Context, parentID *string) ([]*PlatformGroup, error) {
	return PlatformGroupsResolver(ctx, r.IdentityClient, parentID)
}

// MyManagedGroups is the resolver for the myManagedGroups field.
func (r *queryResolver) MyManagedGroups(ctx context.Context) ([]*PlatformGroup, error) {
	return MyManagedGroupsResolver(ctx, r.IdentityClient)
}

// ListUserSessions is the resolver for the listUserSessions field.
func (r *queryResolver) ListUserSessions(ctx context.Context, userID string) ([]*Session, error) {
	return ListUserSessionsResolver(ctx, r.IdentityAdminClient, userID)
}

// MyFactors is the resolver for the myFactors field.
func (r *queryResolver) MyFactors(ctx context.Context) ([]*UserFactor, error) {
	return MyFactorsResolver(ctx, r.IdentityClient)
}

// MyWebauthnCredentials is the resolver for the myWebauthnCredentials field.
func (r *queryResolver) MyWebauthnCredentials(ctx context.Context) ([]*WebauthnCredentialInfo, error) {
	return MyWebauthnCredentialsResolver(ctx, r.IdentityClient)
}

// UserFactors is the resolver for the userFactors field.
func (r *queryResolver) UserFactors(ctx context.Context, userID string) ([]*MfaFactor, error) {
	return UserFactorsResolver(ctx, r.IdentityAdminClient, userID)
}

// ImpersonationStatus is the resolver for the impersonationStatus field.
func (r *queryResolver) ImpersonationStatus(ctx context.Context) (*ImpersonationSession, error) {
	sid, _ := bff.SessionIDFromContext(ctx)
	return ImpersonationStatusResolver(ctx, r.SessionStore, sid, r.IdentityClient, time.Now)
}
