// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// LiveEvents is the resolver for the liveEvents field.
func (r *subscriptionResolver) LiveEvents(ctx context.Context, topics []string) (<-chan *LiveEvent, error) {
	return liveEventsResolver(ctx, r.Bus, topics)
}
