// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolvers

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AICitation struct {
	PolicyID     string  `json:"policyId"`
	PolicyTitle  string  `json:"policyTitle"`
	VersionNo    int     `json:"versionNo"`
	VersionID    string  `json:"versionId"`
	SectionKey   string  `json:"sectionKey"`
	ChunkID      *string `json:"chunkId,omitempty"`
	ChunkIndex   *int    `json:"chunkIndex,omitempty"`
	DocumentType *string `json:"documentType,omitempty"`
}

type AIConfig struct {
	Enabled         bool          `json:"enabled"`
	Provider        *AIProvider   `json:"provider,omitempty"`
	Model           string        `json:"model"`
	BaseURL         string        `json:"baseUrl"`
	Region          string        `json:"region"`
	Deployment      string        `json:"deployment"`
	CredentialSet   bool          `json:"credentialSet"`
	CredentialLast4 string        `json:"credentialLast4"`
	TopK            int           `json:"topK"`
	DataNotice      *AIDataNotice `json:"dataNotice"`
}

type AICredentialStatus struct {
	CredentialSet   bool   `json:"credentialSet"`
	CredentialLast4 string `json:"credentialLast4"`
}

type AIDataNotice struct {
	CurrentVersion  string  `json:"currentVersion"`
	AcceptedVersion string  `json:"acceptedVersion"`
	AcceptedBy      *string `json:"acceptedBy,omitempty"`
	AcceptedAt      *string `json:"acceptedAt,omitempty"`
}

type AIHealth struct {
	Available bool `json:"available"`
	// Populated only when available is false: "ai_service_unavailable" (the ai
	// service is unreachable), "disabled_by_admin" (the module switch is off; ai
	// refuses every intake call while it is, site admins included), or
	// "provider_unavailable" (the configured model provider is failing or not
	// configured). Null when available is true.
	Reason *string `json:"reason,omitempty"`
}

type AIJobResult struct {
	JobID      string     `json:"jobId"`
	Phase      AIJobPhase `json:"phase"`
	ResultRef  *string    `json:"resultRef,omitempty"`
	Error      *string    `json:"error,omitempty"`
	FinishedAt *string    `json:"finishedAt,omitempty"`
}

type AIJobResultContent struct {
	Operation  string `json:"operation"`
	ResultJSON string `json:"resultJson"`
}

type AIJobStatus struct {
	JobID      string     `json:"jobId"`
	Phase      AIJobPhase `json:"phase"`
	ResultRef  *string    `json:"resultRef,omitempty"`
	Error      *string    `json:"error,omitempty"`
	StartedAt  *string    `json:"startedAt,omitempty"`
	FinishedAt *string    `json:"finishedAt,omitempty"`
}

type AIProviderConfigInput struct {
	Provider   AIProvider `json:"provider"`
	Model      *string    `json:"model,omitempty"`
	BaseURL    *string    `json:"baseUrl,omitempty"`
	Region     *string    `json:"region,omitempty"`
	Deployment *string    `json:"deployment,omitempty"`
}

type AIProviderTestResult struct {
	Ok        bool    `json:"ok"`
	Reason    *string `json:"reason,omitempty"`
	LatencyMs int     `json:"latencyMs"`
}

type AIRetrievalConfig struct {
	// The current EFFECTIVE retrieval candidate count (top_k) used when the ai
	// service gathers policy chunks before ranking. DB-configured when a
	// site-admin has set one, else the bootstrap default (50). The server clamps
	// to a ceiling, so this is the value actually in force. Not a secret —
	// returned verbatim for the admin Settings page.
	TopK int `json:"topK"`
}

type AIUserQueryLimit struct {
	// The target user's now-effective per-day AI query limit. Meaningless when
	// unlimited is true.
	EffectiveLimit int `json:"effectiveLimit"`
	// True when the user has no per-day cap (limit set to -1).
	Unlimited bool `json:"unlimited"`
	// True when the user has no override and is therefore governed by the global
	// default limit.
	IsDefault bool `json:"isDefault"`
}

type AccountMergePreview struct {
	SourceUserID              string              `json:"sourceUserId"`
	TargetUserID              string              `json:"targetUserId"`
	Counts                    *MergeCounts        `json:"counts"`
	Items                     []*MergePreviewItem `json:"items"`
	Warnings                  []*MergeWarning     `json:"warnings"`
	RequiresPrivilegedConfirm bool                `json:"requiresPrivilegedConfirm"`
}

type AckActivityDay struct {
	Date  string `json:"date"`
	Acks  int    `json:"acks"`
	Views int    `json:"views"`
}

type AckExport struct {
	Data        string `json:"data"`
	ContentType string `json:"contentType"`
}

type AckRoster struct {
	Acked   []*AckRosterEntry `json:"acked"`
	Pending []*AckRosterEntry `json:"pending"`
}

type AckRosterEntry struct {
	UserID   string  `json:"userId"`
	Email    string  `json:"email"`
	UserName *string `json:"userName,omitempty"`
	AckedAt  *string `json:"ackedAt,omitempty"`
}

type AckStatus struct {
	Acknowledged bool    `json:"acknowledged"`
	AckedAt      *string `json:"ackedAt,omitempty"`
}

type AckSummary struct {
	Required int `json:"required"`
	Done     int `json:"done"`
}

type Acknowledgment struct {
	ID              string `json:"id"`
	UserID          string `json:"userId"`
	PolicyVersionID string `json:"policyVersionId"`
	AckedAt         string `json:"ackedAt"`
}

type AddOrganizationInput struct {
	OrgName     string           `json:"orgName"`
	Domain      string           `json:"domain"`
	Protocol    string           `json:"protocol"`
	DisplayName *string          `json:"displayName,omitempty"`
	Config      []*KeyValueInput `json:"config,omitempty"`
	SecretRef   *string          `json:"secretRef,omitempty"`
}

type Announcement struct {
	Enabled bool   `json:"enabled"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

type AnnouncementInput struct {
	Enabled bool   `json:"enabled"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

type AnonymousReportReceipt struct {
	CaseCode string `json:"caseCode"`
}

type AnswerSegment struct {
	Start   int              `json:"start"`
	End     int              `json:"end"`
	Sources []*SegmentSource `json:"sources"`
}

type Appendix struct {
	ID              string `json:"id"`
	PolicyVersionID string `json:"policyVersionId"`
	Title           string `json:"title"`
	ContentJSON     string `json:"contentJson"`
	OrderIndex      int    `json:"orderIndex"`
	Letter          string `json:"letter"`
}

type AssignmentHistoryEntry struct {
	ID               string  `json:"id"`
	AssignmentID     string  `json:"assignmentId"`
	Event            string  `json:"event"`
	ActorUserID      string  `json:"actorUserId"`
	ActorRole        *string `json:"actorRole,omitempty"`
	PreviousUserID   *string `json:"previousUserId,omitempty"`
	NewUserID        *string `json:"newUserId,omitempty"`
	OutOfEligibility bool    `json:"outOfEligibility"`
	Reason           *string `json:"reason,omitempty"`
	CreatedAt        string  `json:"createdAt"`
	ActorName        *string `json:"actorName,omitempty"`
	PreviousUserName *string `json:"previousUserName,omitempty"`
	NewUserName      *string `json:"newUserName,omitempty"`
}

type AuditChainVerification struct {
	Valid          bool     `json:"valid"`
	RecordsChecked int      `json:"recordsChecked"`
	Errors         []string `json:"errors"`
}

type AuditCheckpoint struct {
	CheckpointUUID string `json:"checkpointUuid"`
	MerkleRoot     string `json:"merkleRoot"`
	AnchorType     string `json:"anchorType"`
	AnchorURL      string `json:"anchorUrl"`
	TsaToken       string `json:"tsaToken"`
	AnchoredAt     string `json:"anchoredAt"`
}

type AuditQueryPage struct {
	Records       []*AuditRecord `json:"records"`
	NextPageToken string         `json:"nextPageToken"`
}

type AuditRecord struct {
	ID               string  `json:"id"`
	RecordUUID       string  `json:"recordUuid"`
	Tier             string  `json:"tier"`
	Action           string  `json:"action"`
	ActorUserID      string  `json:"actorUserId"`
	Subject          string  `json:"subject"`
	GroupID          string  `json:"groupId"`
	OccurredAt       string  `json:"occurredAt"`
	PrevHash         string  `json:"prevHash"`
	RecordHash       string  `json:"recordHash"`
	LegalBasisExempt bool    `json:"legalBasisExempt"`
	ActorName        *string `json:"actorName,omitempty"`
	GroupName        *string `json:"groupName,omitempty"`
	SubjectLabel     *string `json:"subjectLabel,omitempty"`
}

type AuditSegment struct {
	Records     []*AuditRecord     `json:"records"`
	Checkpoints []*AuditCheckpoint `json:"checkpoints"`
}

type AuthoringAssistInput struct {
	PolicyID        string          `json:"policyId"`
	VersionID       string          `json:"versionId"`
	SectionKey      string          `json:"sectionKey"`
	EditableContent string          `json:"editableContent"`
	ContextHint     *string         `json:"contextHint,omitempty"`
	Operation       AssistOperation `json:"operation"`
	Instruction     *string         `json:"instruction,omitempty"`
}

type AuthoringAssistResult struct {
	Suggestion  string `json:"suggestion"`
	OperationID string `json:"operationId"`
}

type Block struct {
	Type        string  `json:"type"`
	ContentJSON *string `json:"contentJson,omitempty"`
}

type BlockInput struct {
	Type        string  `json:"type"`
	ContentJSON *string `json:"contentJson,omitempty"`
}

type BreakGlassResult struct {
	GrantedUntil string `json:"grantedUntil"`
}

type BulkDecideInput struct {
	Decisions []*DecisionInput `json:"decisions"`
}

type BulkDecideResult struct {
	Results     []*DecisionResult `json:"results"`
	BulkBatchID string            `json:"bulkBatchId"`
}

type CaseNote struct {
	ID           string `json:"id"`
	AuthorUserID string `json:"authorUserId"`
	Body         string `json:"body"`
	CreatedAt    string `json:"createdAt"`
}

type CaseNotice struct {
	ID          string          `json:"id"`
	Recipient   NoticeRecipient `json:"recipient"`
	Label       string          `json:"label"`
	Method      string          `json:"method"`
	DaysAllowed int             `json:"daysAllowed"`
	DueOn       string          `json:"dueOn"`
	Status      NoticeStatus    `json:"status"`
	SentOn      *string         `json:"sentOn,omitempty"`
}

type CaseQueue struct {
	Cases  []*CaseSummary     `json:"cases"`
	Counts []*CaseStatusCount `json:"counts"`
}

type CaseStatusCount struct {
	Status CaseStatus `json:"status"`
	Count  int        `json:"count"`
}

type CaseSummary struct {
	ID             string     `json:"id"`
	CaseCode       string     `json:"caseCode"`
	Kind           ReportKind `json:"kind"`
	Status         CaseStatus `json:"status"`
	Summary        string     `json:"summary"`
	AssigneeUserID *string    `json:"assigneeUserId,omitempty"`
	ReceivedAt     string     `json:"receivedAt"`
	NextDeadline   *string    `json:"nextDeadline,omitempty"`
}

type Category struct {
	ID                  string        `json:"id"`
	Name                string        `json:"name"`
	Slug                string        `json:"slug"`
	ParentID            *string       `json:"parentId,omitempty"`
	DefaultTemplateID   *string       `json:"defaultTemplateId,omitempty"`
	DefaultTemplateNone bool          `json:"defaultTemplateNone"`
	DefaultWorkflowID   *string       `json:"defaultWorkflowId,omitempty"`
	Owners              []string      `json:"owners"`
	IdpGroupIds         []string      `json:"idpGroupIds,omitempty"`
	AckTriggers         AckTrigger    `json:"ackTriggers"`
	ReviewCadence       ReviewCadence `json:"reviewCadence"`
	ReviewDate          *string       `json:"reviewDate,omitempty"`
	ExclusionGroupIds   []string      `json:"exclusionGroupIds,omitempty"`
	AckEveryone         bool          `json:"ackEveryone"`
	AckEveryoneSet      bool          `json:"ackEveryoneSet"`
}

type CategoryApprovers struct {
	CategoryID  string   `json:"categoryId"`
	ApproverIds []string `json:"approverIds"`
}

type CategoryApproversInput struct {
	CategoryID  string   `json:"categoryId"`
	ApproverIds []string `json:"approverIds"`
}

type CategoryPref struct {
	Category  NotifCategory `json:"category"`
	Cadence   NotifCadence  `json:"cadence"`
	Mandatory bool          `json:"mandatory"`
}

type CategoryRuleset struct {
	CategoryID string      `json:"categoryId"`
	Rules      []*RaciRule `json:"rules"`
}

type CompletionReport struct {
	TotalAudience       int             `json:"totalAudience"`
	TotalAcked          int             `json:"totalAcked"`
	CompletionPct       float64         `json:"completionPct"`
	AvgDaysToAck        float64         `json:"avgDaysToAck"`
	ViewedNotAckedCount int             `json:"viewedNotAckedCount"`
	Overdue             []*OverdueEntry `json:"overdue"`
}

type ContactBlock struct {
	ID          string  `json:"id"`
	Label       string  `json:"label"`
	Name        *string `json:"name,omitempty"`
	Role        *string `json:"role,omitempty"`
	Department  *string `json:"department,omitempty"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Hours       *string `json:"hours,omitempty"`
	Notes       *string `json:"notes,omitempty"`
	Archived    bool    `json:"archived"`
	UsedByCount int     `json:"usedByCount"`
}

type ContactBlockInput struct {
	Label      string  `json:"label"`
	Name       *string `json:"name,omitempty"`
	Role       *string `json:"role,omitempty"`
	Department *string `json:"department,omitempty"`
	Email      *string `json:"email,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Hours      *string `json:"hours,omitempty"`
	Notes      *string `json:"notes,omitempty"`
}

type CorrectiveAction struct {
	Description string  `json:"description"`
	PolicyID    *string `json:"policyId,omitempty"`
}

type CorrectiveActionInput struct {
	Description string  `json:"description"`
	PolicyID    *string `json:"policyId,omitempty"`
}

type DecisionInput struct {
	PolicyVersionID string       `json:"policyVersionId"`
	StageIndex      int          `json:"stageIndex"`
	Decision        DecisionType `json:"decision"`
	Comment         string       `json:"comment"`
}

type DecisionResult struct {
	PolicyVersionID string  `json:"policyVersionId"`
	StageIndex      int     `json:"stageIndex"`
	Ok              bool    `json:"ok"`
	Error           *string `json:"error,omitempty"`
	AssignmentID    *string `json:"assignmentId,omitempty"`
}

type DefinitionEntry struct {
	ID              string  `json:"id"`
	CategoryID      string  `json:"categoryId"`
	Term            string  `json:"term"`
	Definition      string  `json:"definition"`
	Archived        bool    `json:"archived"`
	CreatedByUserID *string `json:"createdByUserId,omitempty"`
	UsedByCount     int     `json:"usedByCount"`
}

type DefinitionEntryInput struct {
	CategoryID string `json:"categoryId"`
	Term       string `json:"term"`
	Definition string `json:"definition"`
}

type DeleteUserResult struct {
	UserID          string `json:"userId"`
	RevokedSessions int    `json:"revokedSessions"`
}

type DigestWindow struct {
	DailyHour int `json:"dailyHour"`
	WeeklyDow int `json:"weeklyDow"`
}

type DomainVerification struct {
	Token          string `json:"token"`
	DNSRecordName  string `json:"dnsRecordName"`
	DNSRecordValue string `json:"dnsRecordValue"`
	Instructions   string `json:"instructions"`
}

type EffectiveGovernance struct {
	AckAudienceGroups []string `json:"ackAudienceGroups,omitempty"`
	ExclusionGroups   []string `json:"exclusionGroups,omitempty"`
	AckEveryone       bool     `json:"ackEveryone"`
}

type EffectiveTemplate struct {
	TemplateID        string `json:"templateId"`
	TemplateVersionID string `json:"templateVersionId"`
	None              bool   `json:"none"`
}

type EffectiveWorkflow struct {
	WorkflowDefID       *string `json:"workflowDefId,omitempty"`
	HasWorkflow         bool    `json:"hasWorkflow"`
	Usable              bool    `json:"usable"`
	FirstUnstaffedStage *string `json:"firstUnstaffedStage,omitempty"`
}

type EmailServiceConfigInput struct {
	// WRITE-ONLY, presence-tracked. The sending api key. Stored server-side and
	// never read back (see apiKeySet). Nullable so the field carries three states
	// on save: omitted/null leaves the stored key unchanged (persist non-secret
	// fields without re-sending the key); an empty string "" clears the stored key;
	// a non-empty value sets it.
	APIKey      *string `json:"apiKey,omitempty"`
	Provider    string  `json:"provider"`
	Domain      string  `json:"domain"`
	Region      string  `json:"region"`
	FromAddress string  `json:"fromAddress"`
	Enabled     bool    `json:"enabled"`
}

type EmailServiceConfigStatus struct {
	// Whether a sending key is currently stored. The key's value is never returned
	// by any query, only this presence flag, so the admin Settings page can show
	// "a key is stored and not retrievable; you can only replace it" versus "no key
	// set" without the value ever leaving core.
	APIKeySet bool `json:"apiKeySet"`
	// The provider the configuration is for; empty until an admin sets one.
	Provider    string `json:"provider"`
	Domain      string `json:"domain"`
	Region      string `json:"region"`
	FromAddress string `json:"fromAddress"`
	Enabled     bool   `json:"enabled"`
}

type EnrichmentOptOutInput struct {
	Definitions *bool `json:"definitions,omitempty"`
	Related     *bool `json:"related,omitempty"`
	References  *bool `json:"references,omitempty"`
}

type GlobalSettings struct {
	Announcement *Announcement `json:"announcement"`
	Maintenance  *Maintenance  `json:"maintenance"`
}

type GlobalSettingsInput struct {
	Announcement *AnnouncementInput `json:"announcement"`
	Maintenance  *MaintenanceInput  `json:"maintenance"`
}

type GroupMapping struct {
	ID                 string `json:"id"`
	ConnectionID       string `json:"connectionId"`
	IdpGroupClaimValue string `json:"idpGroupClaimValue"`
	TargetGroupID      string `json:"targetGroupId"`
}

type GroupMembership struct {
	GroupID string `json:"groupId"`
	Source  string `json:"source"`
}

type GroupUnit struct {
	GroupID        string   `json:"groupId"`
	InternalQuorum string   `json:"internalQuorum"`
	MemberUserIds  []string `json:"memberUserIds"`
}

type GroupUnitInput struct {
	GroupID        string   `json:"groupId"`
	InternalQuorum string   `json:"internalQuorum"`
	MemberUserIds  []string `json:"memberUserIds"`
}

type HealthStatus struct {
	Status string `json:"status"`
}

type ImpersonationSession struct {
	TargetUserID string `json:"targetUserId"`
	TargetName   string `json:"targetName"`
	Reason       string `json:"reason"`
	StartedAt    string `json:"startedAt"`
	ExpiresAt    string `json:"expiresAt"`
}

type IssueCollabTokenInput struct {
	PolicyID          string  `json:"policyId"`
	DraftID           string  `json:"draftId"`
	TemplateVersionID *string `json:"templateVersionId,omitempty"`
}

type IssueCollabTokenPayload struct {
	Token     string `json:"token"`
	WsURL     string `json:"wsUrl"`
	ExpiresAt string `json:"expiresAt"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LiveEvent struct {
	Type        string  `json:"type"`
	EntityID    *string `json:"entityId,omitempty"`
	GroupID     *string `json:"groupId,omitempty"`
	ActorUserID *string `json:"actorUserId,omitempty"`
	At          string  `json:"at"`
}

type MagicLink struct {
	Token     string `json:"token"`
	ExpiresAt string `json:"expiresAt"`
}

type Maintenance struct {
	Enabled bool   `json:"enabled"`
	Message string `json:"message"`
}

type MaintenanceInput struct {
	Enabled bool   `json:"enabled"`
	Message string `json:"message"`
}

type MergeAccountsResult struct {
	MergeOperationID string             `json:"mergeOperationId"`
	Status           MergeStatus        `json:"status"`
	Counts           *MergeCounts       `json:"counts"`
	Steps            []*MergeStepResult `json:"steps"`
}

type MergeCounts struct {
	PoliciesOwned          int `json:"policiesOwned"`
	RaciGrants             int `json:"raciGrants"`
	AcknowledgmentsMoved   int `json:"acknowledgmentsMoved"`
	AcknowledgmentsDeduped int `json:"acknowledgmentsDeduped"`
	WorkflowItems          int `json:"workflowItems"`
	Preferences            int `json:"preferences"`
}

type MergePreviewItem struct {
	Kind   MergeItemKind `json:"kind"`
	RefID  string        `json:"refId"`
	Label  string        `json:"label"`
	Detail string        `json:"detail"`
}

type MergeStepResult struct {
	Step   string          `json:"step"`
	Status MergeStepStatus `json:"status"`
	Detail string          `json:"detail"`
	Error  string          `json:"error"`
}

type MergeWarning struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type MfaFactor struct {
	ID         string  `json:"id"`
	Kind       string  `json:"kind"`
	EnrolledAt *string `json:"enrolledAt,omitempty"`
	Label      *string `json:"label,omitempty"`
}

type Mutation struct {
}

type MyReport struct {
	CaseID string        `json:"caseId"`
	Report *ReporterView `json:"report"`
}

type NamedReportReceipt struct {
	CaseID   string `json:"caseId"`
	CaseCode string `json:"caseCode"`
}

type NotifTypeDef struct {
	Kind      string        `json:"kind"`
	Category  NotifCategory `json:"category"`
	Mandatory bool          `json:"mandatory"`
	Delivery  NotifDelivery `json:"delivery"`
}

type NotificationPref struct {
	UserID string `json:"userId"`
	Email  bool   `json:"email"`
	InApp  bool   `json:"inApp"`
	Push   bool   `json:"push"`
}

type NotificationPrefInput struct {
	Email bool `json:"email"`
	InApp bool `json:"inApp"`
	Push  bool `json:"push"`
}

type NotificationSettings struct {
	Channels   *NotificationPref `json:"channels"`
	Categories []*CategoryPref   `json:"categories"`
	Overrides  []*TypePref       `json:"overrides"`
	Digest     *DigestWindow     `json:"digest"`
}

type Obligation struct {
	PolicyID        string `json:"policyId"`
	Number          string `json:"number"`
	Title           string `json:"title"`
	Version         string `json:"version"`
	PolicyVersionID string `json:"policyVersionId"`
}

type Organization struct {
	Domain          string `json:"domain"`
	OrgName         string `json:"orgName"`
	Protocol        string `json:"protocol"`
	DisplayName     string `json:"displayName"`
	ConnectionAlias string `json:"connectionAlias"`
	Verified        bool   `json:"verified"`
	TestPassed      bool   `json:"testPassed"`
	Enabled         bool   `json:"enabled"`
	ConnectionID    string `json:"connectionId"`
	JitEnabled      bool   `json:"jitEnabled"`
	AllowLocal      bool   `json:"allowLocal"`
}

type OverdueEntry struct {
	UserID   string  `json:"userId"`
	Email    string  `json:"email"`
	UserName *string `json:"userName,omitempty"`
}

type PDFDownloadLink struct {
	SignedURL string `json:"signedUrl"`
	ExpiresAt string `json:"expiresAt"`
}

type PDFExportJob struct {
	JobID string `json:"jobId"`
}

type PendingTask struct {
	TaskID          string  `json:"taskId"`
	RunID           string  `json:"runId"`
	PolicyVersionID string  `json:"policyVersionId"`
	PolicyTitle     string  `json:"policyTitle"`
	StageIndex      int     `json:"stageIndex"`
	DueAt           *string `json:"dueAt,omitempty"`
}

type Policy struct {
	ID                        string           `json:"id"`
	HomeCategoryID            string           `json:"homeCategoryId"`
	Number                    string           `json:"number"`
	Title                     string           `json:"title"`
	Sensitivity               Sensitivity      `json:"sensitivity"`
	DocumentType              DocumentType     `json:"documentType"`
	OwnerUserID               string           `json:"ownerUserId"`
	OwnerName                 *string          `json:"ownerName,omitempty"`
	CreatedAt                 *string          `json:"createdAt,omitempty"`
	CurrentPublishedVersionID *string          `json:"currentPublishedVersionId,omitempty"`
	CurrentDraftVersionID     *string          `json:"currentDraftVersionId,omitempty"`
	TemplateID                *string          `json:"templateId,omitempty"`
	TemplateNone              bool             `json:"templateNone"`
	TemplateUpdateAvailable   bool             `json:"templateUpdateAvailable"`
	AckTriggers               *AckTrigger      `json:"ackTriggers,omitempty"`
	AckAudienceOverride       []string         `json:"ackAudienceOverride,omitempty"`
	ViewerCan                 *PolicyViewerCan `json:"viewerCan"`
	RetiredAt                 *string          `json:"retiredAt,omitempty"`
}

type PolicyDiff struct {
	Sections []*SectionDiff `json:"sections"`
}

type PolicyOverride struct {
	PolicyNumber string         `json:"policyNumber"`
	Effect       OverrideEffect `json:"effect"`
}

type PolicyRevisionSectionInput struct {
	Key     string `json:"key"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Order   int    `json:"order"`
}

type PolicySummaryResult struct {
	SummaryText string `json:"summaryText"`
	GeneratedAt string `json:"generatedAt"`
}

type PolicyVersion struct {
	ID                string      `json:"id"`
	PolicyID          string      `json:"policyId"`
	VersionNo         int         `json:"versionNo"`
	Status            string      `json:"status"`
	TemplateVersionID string      `json:"templateVersionId"`
	ContentJSON       string      `json:"contentJson"`
	Appendices        []*Appendix `json:"appendices"`
}

type PolicyViewerCan struct {
	Read              bool `json:"read"`
	Edit              bool `json:"edit"`
	Submit            bool `json:"submit"`
	Approve           bool `json:"approve"`
	ContentObfuscated bool `json:"contentObfuscated"`
	CanBreakGlass     bool `json:"canBreakGlass"`
	Ack               bool `json:"ack"`
}

type Query struct {
}

type RaciDecision struct {
	Read          bool   `json:"read"`
	Ack           bool   `json:"ack"`
	Approve       bool   `json:"approve"`
	Author        bool   `json:"author"`
	ReadReason    string `json:"readReason"`
	AckReason     string `json:"ackReason"`
	ApproveReason string `json:"approveReason"`
	AuthorReason  string `json:"authorReason"`
}

type RaciRule struct {
	SubjectKind RaciSubjectKind `json:"subjectKind"`
	SubjectRef  string          `json:"subjectRef"`
	Read        RaciGrant       `json:"read"`
	Ack         RaciGrant       `json:"ack"`
	Approve     RaciGrant       `json:"approve"`
	Author      RaciGrant       `json:"author"`
}

type RaciRuleInput struct {
	SubjectKind RaciSubjectKind `json:"subjectKind"`
	SubjectRef  string          `json:"subjectRef"`
	Read        RaciGrant       `json:"read"`
	Ack         RaciGrant       `json:"ack"`
	Approve     RaciGrant       `json:"approve"`
	Author      RaciGrant       `json:"author"`
}

type ReassignUserPoliciesResult struct {
	ReassignedPolicyIds    []string `json:"reassignedPolicyIds"`
	ReassignedOwnerCount   int      `json:"reassignedOwnerCount"`
	ReassignedAuthorGrants int      `json:"reassignedAuthorGrants"`
}

type Reference struct {
	ID              string        `json:"id"`
	Label           string        `json:"label"`
	Kind            ReferenceKind `json:"kind"`
	Clause          *string       `json:"clause,omitempty"`
	Body            *string       `json:"body,omitempty"`
	URL             *string       `json:"url,omitempty"`
	Archived        bool          `json:"archived"`
	CreatedByUserID *string       `json:"createdByUserId,omitempty"`
	UsedByCount     int           `json:"usedByCount"`
}

type ReferenceDocumentInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ReferenceInput struct {
	Label  string        `json:"label"`
	Kind   ReferenceKind `json:"kind"`
	Clause *string       `json:"clause,omitempty"`
	Body   *string       `json:"body,omitempty"`
	URL    *string       `json:"url,omitempty"`
}

type ReindexResult struct {
	VersionID    string `json:"versionId"`
	Sections     int    `json:"sections"`
	RemovedPrior int    `json:"removedPrior"`
}

type RelatedPolicy struct {
	PolicyID string `json:"policyId"`
	Number   string `json:"number"`
	Title    string `json:"title"`
}

type RelatedPolicySuggestion struct {
	PolicyID    string `json:"policyId"`
	PolicyTitle string `json:"policyTitle"`
	CategoryID  string `json:"categoryId"`
	VersionNo   int    `json:"versionNo"`
	// Cosine distance between the two policies' centroids; lower is more related.
	Distance float64 `json:"distance"`
}

type RenamePolicyResult struct {
	Policy         *Policy `json:"policy"`
	Staged         bool    `json:"staged"`
	DraftVersionID *string `json:"draftVersionId,omitempty"`
}

type RenderedContent struct {
	HTML string `json:"html"`
}

type ReportAttachment struct {
	ID               string `json:"id"`
	Filename         string `json:"filename"`
	ContentType      string `json:"contentType"`
	SizeBytes        int    `json:"sizeBytes"`
	MetadataStripped bool   `json:"metadataStripped"`
}

type ReportAttachmentContent struct {
	Attachment *ReportAttachment `json:"attachment"`
	Data       string            `json:"data"`
}

type ReportAttachmentInput struct {
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
	Data        string `json:"data"`
}

type ReportCase struct {
	ID                string              `json:"id"`
	CaseCode          string              `json:"caseCode"`
	Kind              ReportKind          `json:"kind"`
	Status            CaseStatus          `json:"status"`
	Details           *ReportDetails      `json:"details"`
	ReporterUserID    *string             `json:"reporterUserId,omitempty"`
	AssigneeUserID    *string             `json:"assigneeUserId,omitempty"`
	ReceivedAt        string              `json:"receivedAt"`
	DiscoveredOn      *string             `json:"discoveredOn,omitempty"`
	Attachments       []*ReportAttachment `json:"attachments"`
	Thread            []*ThreadMessage    `json:"thread"`
	Notes             []*CaseNote         `json:"notes"`
	Assessment        *RiskAssessment     `json:"assessment,omitempty"`
	Notices           []*CaseNotice       `json:"notices"`
	Outcome           *CaseOutcome        `json:"outcome,omitempty"`
	CorrectiveActions []*CorrectiveAction `json:"correctiveActions"`
	ClosedAt          *string             `json:"closedAt,omitempty"`
}

type ReportDetails struct {
	WhatHappened     string            `json:"whatHappened"`
	Occurred         string            `json:"occurred"`
	Location         string            `json:"location"`
	InformationKinds []InformationKind `json:"informationKinds"`
	StillHappening   *ReportAnswer     `json:"stillHappening,omitempty"`
}

type ReportDetailsInput struct {
	WhatHappened     string            `json:"whatHappened"`
	Occurred         *string           `json:"occurred,omitempty"`
	Location         *string           `json:"location,omitempty"`
	InformationKinds []InformationKind `json:"informationKinds,omitempty"`
	StillHappening   *ReportAnswer     `json:"stillHappening,omitempty"`
}

type ReporterView struct {
	CaseCode   string           `json:"caseCode"`
	Status     CaseStatus       `json:"status"`
	Details    *ReportDetails   `json:"details"`
	Thread     []*ThreadMessage `json:"thread"`
	ReceivedAt string           `json:"receivedAt"`
}

type RiskAssessment struct {
	Factors         *RiskFactors    `json:"factors"`
	Suggestion      *RiskSuggestion `json:"suggestion,omitempty"`
	Decision        *BreachDecision `json:"decision,omitempty"`
	Reason          string          `json:"reason"`
	DecidedByUserID string          `json:"decidedByUserId"`
	DecidedAt       string          `json:"decidedAt"`
}

type RiskFactors struct {
	Information []InformationKind `json:"information"`
	Recipient   *RiskRecipient    `json:"recipient,omitempty"`
	Viewed      *RiskViewed       `json:"viewed,omitempty"`
	Mitigation  *RiskMitigation   `json:"mitigation,omitempty"`
}

type RiskFactorsInput struct {
	Information []InformationKind `json:"information"`
	Recipient   RiskRecipient     `json:"recipient"`
	Viewed      RiskViewed        `json:"viewed"`
	Mitigation  RiskMitigation    `json:"mitigation"`
}

type RoleScopes struct {
	Author   []string `json:"author"`
	Approver []string `json:"approver"`
}

type SearchAndAnswerResult struct {
	Answer             string           `json:"answer"`
	Citations          []*AICitation    `json:"citations"`
	NoAuthorizedSource bool             `json:"noAuthorizedSource"`
	Segments           []*AnswerSegment `json:"segments"`
	HasSensitiveSource bool             `json:"hasSensitiveSource"`
}

type Section struct {
	Key      string   `json:"key"`
	Title    string   `json:"title"`
	Order    int      `json:"order"`
	Level    int      `json:"level"`
	Required bool     `json:"required"`
	Blocks   []*Block `json:"blocks"`
}

type SectionDiff struct {
	SectionKey    string  `json:"sectionKey"`
	SectionTitle  string  `json:"sectionTitle"`
	ChangeType    string  `json:"changeType"`
	WordDiffHTML  *string `json:"wordDiffHtml,omitempty"`
	IsBoilerplate bool    `json:"isBoilerplate"`
}

type SectionInput struct {
	Key      string        `json:"key"`
	Title    string        `json:"title"`
	Order    int           `json:"order"`
	Level    *int          `json:"level,omitempty"`
	Required *bool         `json:"required,omitempty"`
	Blocks   []*BlockInput `json:"blocks"`
}

type SegmentSource struct {
	PolicyID   string `json:"policyId"`
	VersionID  string `json:"versionId"`
	SectionKey string `json:"sectionKey"`
	ChunkID    string `json:"chunkId"`
	ChunkIndex int    `json:"chunkIndex"`
}

type Session struct {
	SessionID       string `json:"sessionId"`
	UserID          string `json:"userId"`
	IssuedAt        string `json:"issuedAt"`
	AuthenticatedAt string `json:"authenticatedAt"`
	ExpiresAt       string `json:"expiresAt"`
	Active          bool   `json:"active"`
	UserAgent       string `json:"userAgent"`
}

type SpCertificate struct {
	Serial        string `json:"serial"`
	CertPem       string `json:"certPem"`
	SpMetadataXML string `json:"spMetadataXml"`
	NotAfter      string `json:"notAfter"`
	Active        bool   `json:"active"`
}

type StageAssignee struct {
	UserID    string  `json:"userId"`
	Name      *string `json:"name,omitempty"`
	State     string  `json:"state"`
	Comment   *string `json:"comment,omitempty"`
	DecidedAt *string `json:"decidedAt,omitempty"`
	GroupID   *string `json:"groupId,omitempty"`
}

type StageEligibleAssignees struct {
	StageIndex int          `json:"stageIndex"`
	StageName  string       `json:"stageName"`
	Assignees  []*UserLabel `json:"assignees"`
}

type StageUnitProgress struct {
	GroupID   string  `json:"groupId"`
	GroupName *string `json:"groupName,omitempty"`
	Quorum    string  `json:"quorum"`
	Required  int     `json:"required"`
	Approvals int     `json:"approvals"`
	Pending   int     `json:"pending"`
	Roster    int     `json:"roster"`
	Status    string  `json:"status"`
}

type SubmitDraftGenerationInput struct {
	CategoryID         *string                              `json:"categoryId,omitempty"`
	Title              *string                              `json:"title,omitempty"`
	Brief              string                               `json:"brief"`
	Sections           []*SubmitDraftGenerationSectionInput `json:"sections"`
	ReferenceHints     []string                             `json:"referenceHints,omitempty"`
	ReferenceDocuments []*ReferenceDocumentInput            `json:"referenceDocuments,omitempty"`
	EnrichmentOptOut   *EnrichmentOptOutInput               `json:"enrichmentOptOut,omitempty"`
}

type SubmitDraftGenerationResult struct {
	JobID string `json:"jobId"`
}

type SubmitDraftGenerationSectionInput struct {
	Key      string  `json:"key"`
	Title    string  `json:"title"`
	Guidance *string `json:"guidance,omitempty"`
	Order    int     `json:"order"`
}

type SubmitEnrichmentSuggestionsInput struct {
	PolicyID         string                                     `json:"policyId"`
	VersionID        *string                                    `json:"versionId,omitempty"`
	CategoryID       *string                                    `json:"categoryId,omitempty"`
	Title            *string                                    `json:"title,omitempty"`
	Sections         []*SubmitEnrichmentSuggestionsSectionInput `json:"sections"`
	EnrichmentOptOut *EnrichmentOptOutInput                     `json:"enrichmentOptOut,omitempty"`
}

type SubmitEnrichmentSuggestionsSectionInput struct {
	Key     string `json:"key"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SubmitPolicyReviewInput struct {
	PolicyID          string                            `json:"policyId"`
	VersionID         string                            `json:"versionId"`
	CategoryID        *string                           `json:"categoryId,omitempty"`
	Title             *string                           `json:"title,omitempty"`
	Sections          []*SubmitPolicyReviewSectionInput `json:"sections"`
	StandardsRefs     []string                          `json:"standardsRefs,omitempty"`
	RelatedPolicyRefs []string                          `json:"relatedPolicyRefs,omitempty"`
	EnrichmentOptOut  *EnrichmentOptOutInput            `json:"enrichmentOptOut,omitempty"`
}

type SubmitPolicyReviewResult struct {
	JobID string `json:"jobId"`
}

type SubmitPolicyReviewSectionInput struct {
	Key     string `json:"key"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SubmitPolicyRevisionInput struct {
	PolicyID         string                        `json:"policyId"`
	VersionID        string                        `json:"versionId"`
	Instruction      string                        `json:"instruction"`
	Sections         []*PolicyRevisionSectionInput `json:"sections"`
	EnrichmentOptOut *EnrichmentOptOutInput        `json:"enrichmentOptOut,omitempty"`
}

type Subscription struct {
}

type SwapAssigneeInput struct {
	PolicyVersionID string `json:"policyVersionId"`
	StageIndex      int    `json:"stageIndex"`
	CurrentUserID   string `json:"currentUserId"`
	NewUserID       string `json:"newUserId"`
	Reason          string `json:"reason"`
	// Must be true when an admin is swapping in a user outside the seat's
	// eligible pool; the swap is audited with out_of_eligibility=true.
	OutOfEligibilityAck *bool `json:"outOfEligibilityAck,omitempty"`
}

type SwapAssigneeResult struct {
	NewAssignmentID  string `json:"newAssignmentId"`
	NewSLADeadlineAt string `json:"newSlaDeadlineAt"`
}

type Template struct {
	ID              string  `json:"id"`
	Code            string  `json:"code"`
	Name            string  `json:"name"`
	OwnerCategoryID *string `json:"ownerCategoryId,omitempty"`
	RetiredAt       *string `json:"retiredAt,omitempty"`
}

type TemplateVersion struct {
	ID         string     `json:"id"`
	TemplateID string     `json:"templateId"`
	VersionNo  int        `json:"versionNo"`
	Status     string     `json:"status"`
	Sections   []*Section `json:"sections"`
}

type ThreadMessage struct {
	ID            string        `json:"id"`
	Author        MessageAuthor `json:"author"`
	OfficerUserID *string       `json:"officerUserId,omitempty"`
	Body          string        `json:"body"`
	CreatedAt     string        `json:"createdAt"`
}

type TotpEnrollment struct {
	OtpauthURI   string  `json:"otpauthUri"`
	SecretMasked *string `json:"secretMasked,omitempty"`
}

type TypePref struct {
	Kind      string        `json:"kind"`
	Category  NotifCategory `json:"category"`
	Cadence   NotifCadence  `json:"cadence"`
	Mandatory bool          `json:"mandatory"`
	Delivery  NotifDelivery `json:"delivery"`
}

type UpcomingApproval struct {
	PolicyVersionID string `json:"policyVersionId"`
	PolicyTitle     string `json:"policyTitle"`
	StageIndex      int    `json:"stageIndex"`
	StageName       string `json:"stageName"`
}

type User struct {
	UserID           string             `json:"userId"`
	Name             string             `json:"name"`
	FirstName        string             `json:"firstName"`
	LastName         string             `json:"lastName"`
	Email            string             `json:"email"`
	Enabled          bool               `json:"enabled"`
	Roles            []string           `json:"roles"`
	Scopes           *RoleScopes        `json:"scopes"`
	GroupIds         []string           `json:"groupIds"`
	IdpGroups        []string           `json:"idpGroups"`
	PolicyOverrides  []*PolicyOverride  `json:"policyOverrides"`
	IsRoot           bool               `json:"isRoot"`
	Permissions      []string           `json:"permissions"`
	LocalAccount     bool               `json:"localAccount"`
	Username         string             `json:"username"`
	NeedsOnboarding  bool               `json:"needsOnboarding"`
	ManagedGroupIds  []string           `json:"managedGroupIds"`
	Memberships      []*GroupMembership `json:"memberships"`
	Locale           string             `json:"locale"`
	DeletedAt        *string            `json:"deletedAt,omitempty"`
	MergedIntoUserID *string            `json:"mergedIntoUserId,omitempty"`
}

type UserDeletionCounts struct {
	PendingApprovals int `json:"pendingApprovals"`
	OwnedPolicies    int `json:"ownedPolicies"`
	RaciGrants       int `json:"raciGrants"`
	Roles            int `json:"roles"`
	Permissions      int `json:"permissions"`
	GroupMemberships int `json:"groupMemberships"`
	IdpGroups        int `json:"idpGroups"`
	PolicyOverrides  int `json:"policyOverrides"`
	BreakGlassGrants int `json:"breakGlassGrants"`
	ManagedGroups    int `json:"managedGroups"`
}

type UserDeletionPreview struct {
	UserID               string                     `json:"userId"`
	Counts               *UserDeletionCounts        `json:"counts"`
	Items                []*UserDeletionPreviewItem `json:"items"`
	Warnings             []*UserDeletionWarning     `json:"warnings"`
	BlocksDelete         bool                       `json:"blocksDelete"`
	LocallyAuthenticable bool                       `json:"locallyAuthenticable"`
}

type UserDeletionPreviewItem struct {
	Kind         DeletionItemKind `json:"kind"`
	RefID        string           `json:"refId"`
	Label        string           `json:"label"`
	Detail       string           `json:"detail"`
	BlocksDelete bool             `json:"blocksDelete"`
}

type UserDeletionWarning struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserFactor struct {
	Kind       string  `json:"kind"`
	EnrolledAt *string `json:"enrolledAt,omitempty"`
	Label      *string `json:"label,omitempty"`
}

type UserLabel struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

type UserPage struct {
	Users         []*User `json:"users"`
	NextPageToken string  `json:"nextPageToken"`
}

type WebauthnCredentialInfo struct {
	ID         string   `json:"id"`
	Label      *string  `json:"label,omitempty"`
	CreatedAt  string   `json:"createdAt"`
	LastUsedAt *string  `json:"lastUsedAt,omitempty"`
	Transports []string `json:"transports,omitempty"`
}

type WebauthnRegistration struct {
	OptionsJSON string `json:"optionsJson"`
	SessionID   string `json:"sessionId"`
}

type WorkflowDef struct {
	ID          string              `json:"id"`
	Name        string              `json:"name"`
	Description *string             `json:"description,omitempty"`
	Version     int                 `json:"version"`
	Stages      []*WorkflowStageDef `json:"stages"`
}

type WorkflowStageDef struct {
	ID                  string               `json:"id"`
	Name                string               `json:"name"`
	Approvers           []string             `json:"approvers"`
	ApproversByCategory []*CategoryApprovers `json:"approversByCategory"`
	GroupUnits          []*GroupUnit         `json:"groupUnits"`
	Quorum              string               `json:"quorum"`
	SLADays             *int                 `json:"slaDays,omitempty"`
	RejectOnSLABreach   *bool                `json:"rejectOnSlaBreach,omitempty"`
	PinnedLast          *bool                `json:"pinnedLast,omitempty"`
}

type WorkflowStageInput struct {
	ID                  *string                   `json:"id,omitempty"`
	Name                string                    `json:"name"`
	Approvers           []string                  `json:"approvers"`
	ApproversByCategory []*CategoryApproversInput `json:"approversByCategory,omitempty"`
	GroupUnits          []*GroupUnitInput         `json:"groupUnits,omitempty"`
	Quorum              string                    `json:"quorum"`
	SLADays             *int                      `json:"slaDays,omitempty"`
	RejectOnSLABreach   *bool                     `json:"rejectOnSlaBreach,omitempty"`
	PinnedLast          *bool                     `json:"pinnedLast,omitempty"`
}

type WorkflowStatus struct {
	Status            ApprovalStatus         `json:"status"`
	RunID             string                 `json:"runId"`
	CurrentStageIdx   int                    `json:"currentStageIdx"`
	StageNames        []string               `json:"stageNames"`
	StageAssignees    [][]*StageAssignee     `json:"stageAssignees"`
	StageUnitProgress [][]*StageUnitProgress `json:"stageUnitProgress"`
}

type WorkflowSubmitResult struct {
	RunID string `json:"runId"`
}

type AIJobPhase string

const (
	AIJobPhaseAiJobPhasePending   AIJobPhase = "AI_JOB_PHASE_PENDING"
	AIJobPhaseAiJobPhaseRunning   AIJobPhase = "AI_JOB_PHASE_RUNNING"
	AIJobPhaseAiJobPhaseSucceeded AIJobPhase = "AI_JOB_PHASE_SUCCEEDED"
	AIJobPhaseAiJobPhaseFailed    AIJobPhase = "AI_JOB_PHASE_FAILED"
)

var AllAIJobPhase = []AIJobPhase{
	AIJobPhaseAiJobPhasePending,
	AIJobPhaseAiJobPhaseRunning,
	AIJobPhaseAiJobPhaseSucceeded,
	AIJobPhaseAiJobPhaseFailed,
}

func (e AIJobPhase) IsValid() bool {
	switch e {
	case AIJobPhaseAiJobPhasePending, AIJobPhaseAiJobPhaseRunning, AIJobPhaseAiJobPhaseSucceeded, AIJobPhaseAiJobPhaseFailed:
		return true
	}
	return false
}

func (e AIJobPhase) String() string {
	return string(e)
}

func (e *AIJobPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AIJobPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AIJobPhase", str)
	}
	return nil
}

func (e AIJobPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AIJobPhase) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AIJobPhase) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AIProvider string

const (
	AIProviderAnthropic        AIProvider = "ANTHROPIC"
	AIProviderOpenai           AIProvider = "OPENAI"
	AIProviderAzureOpenai      AIProvider = "AZURE_OPENAI"
	AIProviderGemini           AIProvider = "GEMINI"
	AIProviderBedrock          AIProvider = "BEDROCK"
	AIProviderOpenaiCompatible AIProvider = "OPENAI_COMPATIBLE"
)

var AllAIProvider = []AIProvider{
	AIProviderAnthropic,
	AIProviderOpenai,
	AIProviderAzureOpenai,
	AIProviderGemini,
	AIProviderBedrock,
	AIProviderOpenaiCompatible,
}

func (e AIProvider) IsValid() bool {
	switch e {
	case AIProviderAnthropic, AIProviderOpenai, AIProviderAzureOpenai, AIProviderGemini, AIProviderBedrock, AIProviderOpenaiCompatible:
		return true
	}
	return false
}

func (e AIProvider) String() string {
	return string(e)
}

func (e *AIProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AIProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AIProvider", str)
	}
	return nil
}

func (e AIProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AIProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AIProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AckTrigger string

const (
	AckTriggerNone      AckTrigger = "NONE"
	AckTriggerOnPublish AckTrigger = "ON_PUBLISH"
	AckTriggerOnChange  AckTrigger = "ON_CHANGE"
)

var AllAckTrigger = []AckTrigger{
	AckTriggerNone,
	AckTriggerOnPublish,
	AckTriggerOnChange,
}

func (e AckTrigger) IsValid() bool {
	switch e {
	case AckTriggerNone, AckTriggerOnPublish, AckTriggerOnChange:
		return true
	}
	return false
}

func (e AckTrigger) String() string {
	return string(e)
}

func (e *AckTrigger) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AckTrigger(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AckTrigger", str)
	}
	return nil
}

func (e AckTrigger) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AckTrigger) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AckTrigger) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ApprovalStatus string

const (
	ApprovalStatusApprovalStatusUnspecified ApprovalStatus = "APPROVAL_STATUS_UNSPECIFIED"
	ApprovalStatusApprovalStatusDraft       ApprovalStatus = "APPROVAL_STATUS_DRAFT"
	ApprovalStatusApprovalStatusInReview    ApprovalStatus = "APPROVAL_STATUS_IN_REVIEW"
	ApprovalStatusApprovalStatusApproved    ApprovalStatus = "APPROVAL_STATUS_APPROVED"
	ApprovalStatusApprovalStatusScheduled   ApprovalStatus = "APPROVAL_STATUS_SCHEDULED"
	ApprovalStatusApprovalStatusPublished   ApprovalStatus = "APPROVAL_STATUS_PUBLISHED"
	ApprovalStatusApprovalStatusSuperseded  ApprovalStatus = "APPROVAL_STATUS_SUPERSEDED"
	ApprovalStatusApprovalStatusRejected    ApprovalStatus = "APPROVAL_STATUS_REJECTED"
	ApprovalStatusApprovalStatusWithdrawn   ApprovalStatus = "APPROVAL_STATUS_WITHDRAWN"
	ApprovalStatusApprovalStatusArchived    ApprovalStatus = "APPROVAL_STATUS_ARCHIVED"
)

var AllApprovalStatus = []ApprovalStatus{
	ApprovalStatusApprovalStatusUnspecified,
	ApprovalStatusApprovalStatusDraft,
	ApprovalStatusApprovalStatusInReview,
	ApprovalStatusApprovalStatusApproved,
	ApprovalStatusApprovalStatusScheduled,
	ApprovalStatusApprovalStatusPublished,
	ApprovalStatusApprovalStatusSuperseded,
	ApprovalStatusApprovalStatusRejected,
	ApprovalStatusApprovalStatusWithdrawn,
	ApprovalStatusApprovalStatusArchived,
}

func (e ApprovalStatus) IsValid() bool {
	switch e {
	case ApprovalStatusApprovalStatusUnspecified, ApprovalStatusApprovalStatusDraft, ApprovalStatusApprovalStatusInReview, ApprovalStatusApprovalStatusApproved, ApprovalStatusApprovalStatusScheduled, ApprovalStatusApprovalStatusPublished, ApprovalStatusApprovalStatusSuperseded, ApprovalStatusApprovalStatusRejected, ApprovalStatusApprovalStatusWithdrawn, ApprovalStatusApprovalStatusArchived:
		return true
	}
	return false
}

func (e ApprovalStatus) String() string {
	return string(e)
}

func (e *ApprovalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApprovalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApprovalStatus", str)
	}
	return nil
}

func (e ApprovalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApprovalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApprovalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssistOperation string

const (
	AssistOperationAssistOperationUnspecified AssistOperation = "ASSIST_OPERATION_UNSPECIFIED"
	AssistOperationAssistOperationDraft       AssistOperation = "ASSIST_OPERATION_DRAFT"
	AssistOperationAssistOperationExpand      AssistOperation = "ASSIST_OPERATION_EXPAND"
	AssistOperationAssistOperationRewrite     AssistOperation = "ASSIST_OPERATION_REWRITE"
	AssistOperationAssistOperationClarify     AssistOperation = "ASSIST_OPERATION_CLARIFY"
	AssistOperationAssistOperationSummarize   AssistOperation = "ASSIST_OPERATION_SUMMARIZE"
)

var AllAssistOperation = []AssistOperation{
	AssistOperationAssistOperationUnspecified,
	AssistOperationAssistOperationDraft,
	AssistOperationAssistOperationExpand,
	AssistOperationAssistOperationRewrite,
	AssistOperationAssistOperationClarify,
	AssistOperationAssistOperationSummarize,
}

func (e AssistOperation) IsValid() bool {
	switch e {
	case AssistOperationAssistOperationUnspecified, AssistOperationAssistOperationDraft, AssistOperationAssistOperationExpand, AssistOperationAssistOperationRewrite, AssistOperationAssistOperationClarify, AssistOperationAssistOperationSummarize:
		return true
	}
	return false
}

func (e AssistOperation) String() string {
	return string(e)
}

func (e *AssistOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssistOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssistOperation", str)
	}
	return nil
}

func (e AssistOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssistOperation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssistOperation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BreachDecision string

const (
	BreachDecisionReportable    BreachDecision = "REPORTABLE"
	BreachDecisionNotReportable BreachDecision = "NOT_REPORTABLE"
)

var AllBreachDecision = []BreachDecision{
	BreachDecisionReportable,
	BreachDecisionNotReportable,
}

func (e BreachDecision) IsValid() bool {
	switch e {
	case BreachDecisionReportable, BreachDecisionNotReportable:
		return true
	}
	return false
}

func (e BreachDecision) String() string {
	return string(e)
}

func (e *BreachDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BreachDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BreachDecision", str)
	}
	return nil
}

func (e BreachDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BreachDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BreachDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CaseOutcome string

const (
	CaseOutcomeSubstantiated    CaseOutcome = "SUBSTANTIATED"
	CaseOutcomeNotSubstantiated CaseOutcome = "NOT_SUBSTANTIATED"
	CaseOutcomeInconclusive     CaseOutcome = "INCONCLUSIVE"
)

var AllCaseOutcome = []CaseOutcome{
	CaseOutcomeSubstantiated,
	CaseOutcomeNotSubstantiated,
	CaseOutcomeInconclusive,
}

func (e CaseOutcome) IsValid() bool {
	switch e {
	case CaseOutcomeSubstantiated, CaseOutcomeNotSubstantiated, CaseOutcomeInconclusive:
		return true
	}
	return false
}

func (e CaseOutcome) String() string {
	return string(e)
}

func (e *CaseOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CaseOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CaseOutcome", str)
	}
	return nil
}

func (e CaseOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CaseOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CaseOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CaseStatus string

const (
	CaseStatusNew                CaseStatus = "NEW"
	CaseStatusInReview           CaseStatus = "IN_REVIEW"
	CaseStatusNeedsReporterReply CaseStatus = "NEEDS_REPORTER_REPLY"
	CaseStatusRiskAssessment     CaseStatus = "RISK_ASSESSMENT"
	CaseStatusNotificationDue    CaseStatus = "NOTIFICATION_DUE"
	CaseStatusClosed             CaseStatus = "CLOSED"
)

var AllCaseStatus = []CaseStatus{
	CaseStatusNew,
	CaseStatusInReview,
	CaseStatusNeedsReporterReply,
	CaseStatusRiskAssessment,
	CaseStatusNotificationDue,
	CaseStatusClosed,
}

func (e CaseStatus) IsValid() bool {
	switch e {
	case CaseStatusNew, CaseStatusInReview, CaseStatusNeedsReporterReply, CaseStatusRiskAssessment, CaseStatusNotificationDue, CaseStatusClosed:
		return true
	}
	return false
}

func (e CaseStatus) String() string {
	return string(e)
}

func (e *CaseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CaseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CaseStatus", str)
	}
	return nil
}

func (e CaseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CaseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CaseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DecisionType string

const (
	DecisionTypeDecisionTypeUnspecified DecisionType = "DECISION_TYPE_UNSPECIFIED"
	DecisionTypeDecisionTypeApprove     DecisionType = "DECISION_TYPE_APPROVE"
	DecisionTypeDecisionTypeReject      DecisionType = "DECISION_TYPE_REJECT"
)

var AllDecisionType = []DecisionType{
	DecisionTypeDecisionTypeUnspecified,
	DecisionTypeDecisionTypeApprove,
	DecisionTypeDecisionTypeReject,
}

func (e DecisionType) IsValid() bool {
	switch e {
	case DecisionTypeDecisionTypeUnspecified, DecisionTypeDecisionTypeApprove, DecisionTypeDecisionTypeReject:
		return true
	}
	return false
}

func (e DecisionType) String() string {
	return string(e)
}

func (e *DecisionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DecisionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DecisionType", str)
	}
	return nil
}

func (e DecisionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DecisionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DecisionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeletionItemKind string

const (
	DeletionItemKindPendingApproval DeletionItemKind = "PENDING_APPROVAL"
	DeletionItemKindOwnedPolicy     DeletionItemKind = "OWNED_POLICY"
	DeletionItemKindRaciGrant       DeletionItemKind = "RACI_GRANT"
	DeletionItemKindAccessRow       DeletionItemKind = "ACCESS_ROW"
	DeletionItemKindCredential      DeletionItemKind = "CREDENTIAL"
)

var AllDeletionItemKind = []DeletionItemKind{
	DeletionItemKindPendingApproval,
	DeletionItemKindOwnedPolicy,
	DeletionItemKindRaciGrant,
	DeletionItemKindAccessRow,
	DeletionItemKindCredential,
}

func (e DeletionItemKind) IsValid() bool {
	switch e {
	case DeletionItemKindPendingApproval, DeletionItemKindOwnedPolicy, DeletionItemKindRaciGrant, DeletionItemKindAccessRow, DeletionItemKindCredential:
		return true
	}
	return false
}

func (e DeletionItemKind) String() string {
	return string(e)
}

func (e *DeletionItemKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeletionItemKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeletionItemKind", str)
	}
	return nil
}

func (e DeletionItemKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeletionItemKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeletionItemKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DocumentType string

const (
	DocumentTypePolicy    DocumentType = "POLICY"
	DocumentTypeProcedure DocumentType = "PROCEDURE"
)

var AllDocumentType = []DocumentType{
	DocumentTypePolicy,
	DocumentTypeProcedure,
}

func (e DocumentType) IsValid() bool {
	switch e {
	case DocumentTypePolicy, DocumentTypeProcedure:
		return true
	}
	return false
}

func (e DocumentType) String() string {
	return string(e)
}

func (e *DocumentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentType", str)
	}
	return nil
}

func (e DocumentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InformationKind string

const (
	InformationKindHealth    InformationKind = "HEALTH"
	InformationKindContact   InformationKind = "CONTACT"
	InformationKindFinancial InformationKind = "FINANCIAL"
	InformationKindNotSure   InformationKind = "NOT_SURE"
)

var AllInformationKind = []InformationKind{
	InformationKindHealth,
	InformationKindContact,
	InformationKindFinancial,
	InformationKindNotSure,
}

func (e InformationKind) IsValid() bool {
	switch e {
	case InformationKindHealth, InformationKindContact, InformationKindFinancial, InformationKindNotSure:
		return true
	}
	return false
}

func (e InformationKind) String() string {
	return string(e)
}

func (e *InformationKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InformationKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InformationKind", str)
	}
	return nil
}

func (e InformationKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InformationKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InformationKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InitiatorRole string

const (
	InitiatorRoleInitiatorRoleUnspecified    InitiatorRole = "INITIATOR_ROLE_UNSPECIFIED"
	InitiatorRoleInitiatorRoleAdmin          InitiatorRole = "INITIATOR_ROLE_ADMIN"
	InitiatorRoleInitiatorRoleSelfDelegate   InitiatorRole = "INITIATOR_ROLE_SELF_DELEGATE"
	InitiatorRoleInitiatorRoleWorkflowAuthor InitiatorRole = "INITIATOR_ROLE_WORKFLOW_AUTHOR"
)

var AllInitiatorRole = []InitiatorRole{
	InitiatorRoleInitiatorRoleUnspecified,
	InitiatorRoleInitiatorRoleAdmin,
	InitiatorRoleInitiatorRoleSelfDelegate,
	InitiatorRoleInitiatorRoleWorkflowAuthor,
}

func (e InitiatorRole) IsValid() bool {
	switch e {
	case InitiatorRoleInitiatorRoleUnspecified, InitiatorRoleInitiatorRoleAdmin, InitiatorRoleInitiatorRoleSelfDelegate, InitiatorRoleInitiatorRoleWorkflowAuthor:
		return true
	}
	return false
}

func (e InitiatorRole) String() string {
	return string(e)
}

func (e *InitiatorRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InitiatorRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InitiatorRole", str)
	}
	return nil
}

func (e InitiatorRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InitiatorRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InitiatorRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MergeItemKind string

const (
	MergeItemKindPolicyOwner    MergeItemKind = "POLICY_OWNER"
	MergeItemKindRaciGrant      MergeItemKind = "RACI_GRANT"
	MergeItemKindAcknowledgment MergeItemKind = "ACKNOWLEDGMENT"
	MergeItemKindWorkflowItem   MergeItemKind = "WORKFLOW_ITEM"
	MergeItemKindPreference     MergeItemKind = "PREFERENCE"
)

var AllMergeItemKind = []MergeItemKind{
	MergeItemKindPolicyOwner,
	MergeItemKindRaciGrant,
	MergeItemKindAcknowledgment,
	MergeItemKindWorkflowItem,
	MergeItemKindPreference,
}

func (e MergeItemKind) IsValid() bool {
	switch e {
	case MergeItemKindPolicyOwner, MergeItemKindRaciGrant, MergeItemKindAcknowledgment, MergeItemKindWorkflowItem, MergeItemKindPreference:
		return true
	}
	return false
}

func (e MergeItemKind) String() string {
	return string(e)
}

func (e *MergeItemKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MergeItemKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MergeItemKind", str)
	}
	return nil
}

func (e MergeItemKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MergeItemKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MergeItemKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MergeStatus string

const (
	MergeStatusCompleted MergeStatus = "COMPLETED"
	MergeStatusPartial   MergeStatus = "PARTIAL"
	MergeStatusFailed    MergeStatus = "FAILED"
)

var AllMergeStatus = []MergeStatus{
	MergeStatusCompleted,
	MergeStatusPartial,
	MergeStatusFailed,
}

func (e MergeStatus) IsValid() bool {
	switch e {
	case MergeStatusCompleted, MergeStatusPartial, MergeStatusFailed:
		return true
	}
	return false
}

func (e MergeStatus) String() string {
	return string(e)
}

func (e *MergeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MergeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MergeStatus", str)
	}
	return nil
}

func (e MergeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MergeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MergeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MergeStepStatus string

const (
	MergeStepStatusPending   MergeStepStatus = "PENDING"
	MergeStepStatusCompleted MergeStepStatus = "COMPLETED"
	MergeStepStatusFailed    MergeStepStatus = "FAILED"
	MergeStepStatusSkipped   MergeStepStatus = "SKIPPED"
)

var AllMergeStepStatus = []MergeStepStatus{
	MergeStepStatusPending,
	MergeStepStatusCompleted,
	MergeStepStatusFailed,
	MergeStepStatusSkipped,
}

func (e MergeStepStatus) IsValid() bool {
	switch e {
	case MergeStepStatusPending, MergeStepStatusCompleted, MergeStepStatusFailed, MergeStepStatusSkipped:
		return true
	}
	return false
}

func (e MergeStepStatus) String() string {
	return string(e)
}

func (e *MergeStepStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MergeStepStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MergeStepStatus", str)
	}
	return nil
}

func (e MergeStepStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MergeStepStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MergeStepStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MessageAuthor string

const (
	MessageAuthorReporter MessageAuthor = "REPORTER"
	MessageAuthorOfficer  MessageAuthor = "OFFICER"
)

var AllMessageAuthor = []MessageAuthor{
	MessageAuthorReporter,
	MessageAuthorOfficer,
}

func (e MessageAuthor) IsValid() bool {
	switch e {
	case MessageAuthorReporter, MessageAuthorOfficer:
		return true
	}
	return false
}

func (e MessageAuthor) String() string {
	return string(e)
}

func (e *MessageAuthor) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageAuthor(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageAuthor", str)
	}
	return nil
}

func (e MessageAuthor) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageAuthor) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageAuthor) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NoticeRecipient string

const (
	NoticeRecipientAffectedPeople NoticeRecipient = "AFFECTED_PEOPLE"
	NoticeRecipientRegulator      NoticeRecipient = "REGULATOR"
	NoticeRecipientMedia          NoticeRecipient = "MEDIA"
	NoticeRecipientOther          NoticeRecipient = "OTHER"
)

var AllNoticeRecipient = []NoticeRecipient{
	NoticeRecipientAffectedPeople,
	NoticeRecipientRegulator,
	NoticeRecipientMedia,
	NoticeRecipientOther,
}

func (e NoticeRecipient) IsValid() bool {
	switch e {
	case NoticeRecipientAffectedPeople, NoticeRecipientRegulator, NoticeRecipientMedia, NoticeRecipientOther:
		return true
	}
	return false
}

func (e NoticeRecipient) String() string {
	return string(e)
}

func (e *NoticeRecipient) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NoticeRecipient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NoticeRecipient", str)
	}
	return nil
}

func (e NoticeRecipient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NoticeRecipient) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NoticeRecipient) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NoticeStatus string

const (
	NoticeStatusNotSent   NoticeStatus = "NOT_SENT"
	NoticeStatusDraft     NoticeStatus = "DRAFT"
	NoticeStatusSent      NoticeStatus = "SENT"
	NoticeStatusNotNeeded NoticeStatus = "NOT_NEEDED"
)

var AllNoticeStatus = []NoticeStatus{
	NoticeStatusNotSent,
	NoticeStatusDraft,
	NoticeStatusSent,
	NoticeStatusNotNeeded,
}

func (e NoticeStatus) IsValid() bool {
	switch e {
	case NoticeStatusNotSent, NoticeStatusDraft, NoticeStatusSent, NoticeStatusNotNeeded:
		return true
	}
	return false
}

func (e NoticeStatus) String() string {
	return string(e)
}

func (e *NoticeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NoticeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NoticeStatus", str)
	}
	return nil
}

func (e NoticeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NoticeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NoticeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotifCadence string

const (
	NotifCadenceImmediate NotifCadence = "IMMEDIATE"
	NotifCadenceDaily     NotifCadence = "DAILY"
	NotifCadenceWeekly    NotifCadence = "WEEKLY"
	NotifCadenceOff       NotifCadence = "OFF"
)

var AllNotifCadence = []NotifCadence{
	NotifCadenceImmediate,
	NotifCadenceDaily,
	NotifCadenceWeekly,
	NotifCadenceOff,
}

func (e NotifCadence) IsValid() bool {
	switch e {
	case NotifCadenceImmediate, NotifCadenceDaily, NotifCadenceWeekly, NotifCadenceOff:
		return true
	}
	return false
}

func (e NotifCadence) String() string {
	return string(e)
}

func (e *NotifCadence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotifCadence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotifCadence", str)
	}
	return nil
}

func (e NotifCadence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotifCadence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotifCadence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotifCategory string

const (
	NotifCategoryCompliance    NotifCategory = "COMPLIANCE"
	NotifCategorySecurity      NotifCategory = "SECURITY"
	NotifCategoryTransactional NotifCategory = "TRANSACTIONAL"
	NotifCategoryWorkflow      NotifCategory = "WORKFLOW"
	NotifCategoryInformational NotifCategory = "INFORMATIONAL"
)

var AllNotifCategory = []NotifCategory{
	NotifCategoryCompliance,
	NotifCategorySecurity,
	NotifCategoryTransactional,
	NotifCategoryWorkflow,
	NotifCategoryInformational,
}

func (e NotifCategory) IsValid() bool {
	switch e {
	case NotifCategoryCompliance, NotifCategorySecurity, NotifCategoryTransactional, NotifCategoryWorkflow, NotifCategoryInformational:
		return true
	}
	return false
}

func (e NotifCategory) String() string {
	return string(e)
}

func (e *NotifCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotifCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotifCategory", str)
	}
	return nil
}

func (e NotifCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotifCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotifCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotifDelivery string

const (
	NotifDeliveryImmediateOnly     NotifDelivery = "IMMEDIATE_ONLY"
	NotifDeliveryImmediateOrDigest NotifDelivery = "IMMEDIATE_OR_DIGEST"
	NotifDeliveryReminderSchedule  NotifDelivery = "REMINDER_SCHEDULE"
	NotifDeliveryDigestPreferred   NotifDelivery = "DIGEST_PREFERRED"
)

var AllNotifDelivery = []NotifDelivery{
	NotifDeliveryImmediateOnly,
	NotifDeliveryImmediateOrDigest,
	NotifDeliveryReminderSchedule,
	NotifDeliveryDigestPreferred,
}

func (e NotifDelivery) IsValid() bool {
	switch e {
	case NotifDeliveryImmediateOnly, NotifDeliveryImmediateOrDigest, NotifDeliveryReminderSchedule, NotifDeliveryDigestPreferred:
		return true
	}
	return false
}

func (e NotifDelivery) String() string {
	return string(e)
}

func (e *NotifDelivery) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotifDelivery(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotifDelivery", str)
	}
	return nil
}

func (e NotifDelivery) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotifDelivery) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotifDelivery) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OverrideEffect string

const (
	OverrideEffectAllow OverrideEffect = "ALLOW"
	OverrideEffectDeny  OverrideEffect = "DENY"
)

var AllOverrideEffect = []OverrideEffect{
	OverrideEffectAllow,
	OverrideEffectDeny,
}

func (e OverrideEffect) IsValid() bool {
	switch e {
	case OverrideEffectAllow, OverrideEffectDeny:
		return true
	}
	return false
}

func (e OverrideEffect) String() string {
	return string(e)
}

func (e *OverrideEffect) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OverrideEffect(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OverrideEffect", str)
	}
	return nil
}

func (e OverrideEffect) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OverrideEffect) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OverrideEffect) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RaciGrant string

const (
	RaciGrantBlank RaciGrant = "BLANK"
	RaciGrantAllow RaciGrant = "ALLOW"
	RaciGrantDeny  RaciGrant = "DENY"
)

var AllRaciGrant = []RaciGrant{
	RaciGrantBlank,
	RaciGrantAllow,
	RaciGrantDeny,
}

func (e RaciGrant) IsValid() bool {
	switch e {
	case RaciGrantBlank, RaciGrantAllow, RaciGrantDeny:
		return true
	}
	return false
}

func (e RaciGrant) String() string {
	return string(e)
}

func (e *RaciGrant) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RaciGrant(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RaciGrant", str)
	}
	return nil
}

func (e RaciGrant) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RaciGrant) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RaciGrant) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RaciSubjectKind string

const (
	RaciSubjectKindEveryone RaciSubjectKind = "EVERYONE"
	RaciSubjectKindGroup    RaciSubjectKind = "GROUP"
	RaciSubjectKindUser     RaciSubjectKind = "USER"
)

var AllRaciSubjectKind = []RaciSubjectKind{
	RaciSubjectKindEveryone,
	RaciSubjectKindGroup,
	RaciSubjectKindUser,
}

func (e RaciSubjectKind) IsValid() bool {
	switch e {
	case RaciSubjectKindEveryone, RaciSubjectKindGroup, RaciSubjectKindUser:
		return true
	}
	return false
}

func (e RaciSubjectKind) String() string {
	return string(e)
}

func (e *RaciSubjectKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RaciSubjectKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RaciSubjectKind", str)
	}
	return nil
}

func (e RaciSubjectKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RaciSubjectKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RaciSubjectKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReferenceKind string

const (
	ReferenceKindStandard ReferenceKind = "STANDARD"
	ReferenceKindText     ReferenceKind = "TEXT"
	ReferenceKindLink     ReferenceKind = "LINK"
)

var AllReferenceKind = []ReferenceKind{
	ReferenceKindStandard,
	ReferenceKindText,
	ReferenceKindLink,
}

func (e ReferenceKind) IsValid() bool {
	switch e {
	case ReferenceKindStandard, ReferenceKindText, ReferenceKindLink:
		return true
	}
	return false
}

func (e ReferenceKind) String() string {
	return string(e)
}

func (e *ReferenceKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReferenceKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReferenceKind", str)
	}
	return nil
}

func (e ReferenceKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReferenceKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReferenceKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportAnswer string

const (
	ReportAnswerYes     ReportAnswer = "YES"
	ReportAnswerNo      ReportAnswer = "NO"
	ReportAnswerNotSure ReportAnswer = "NOT_SURE"
)

var AllReportAnswer = []ReportAnswer{
	ReportAnswerYes,
	ReportAnswerNo,
	ReportAnswerNotSure,
}

func (e ReportAnswer) IsValid() bool {
	switch e {
	case ReportAnswerYes, ReportAnswerNo, ReportAnswerNotSure:
		return true
	}
	return false
}

func (e ReportAnswer) String() string {
	return string(e)
}

func (e *ReportAnswer) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportAnswer(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportAnswer", str)
	}
	return nil
}

func (e ReportAnswer) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportAnswer) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportAnswer) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportKind string

const (
	ReportKindAnonymous ReportKind = "ANONYMOUS"
	ReportKindNamed     ReportKind = "NAMED"
)

var AllReportKind = []ReportKind{
	ReportKindAnonymous,
	ReportKindNamed,
}

func (e ReportKind) IsValid() bool {
	switch e {
	case ReportKindAnonymous, ReportKindNamed:
		return true
	}
	return false
}

func (e ReportKind) String() string {
	return string(e)
}

func (e *ReportKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportKind", str)
	}
	return nil
}

func (e ReportKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewCadence string

const (
	ReviewCadenceNone     ReviewCadence = "NONE"
	ReviewCadenceAnnual   ReviewCadence = "ANNUAL"
	ReviewCadenceBiennial ReviewCadence = "BIENNIAL"
	ReviewCadenceOnDate   ReviewCadence = "ON_DATE"
)

var AllReviewCadence = []ReviewCadence{
	ReviewCadenceNone,
	ReviewCadenceAnnual,
	ReviewCadenceBiennial,
	ReviewCadenceOnDate,
}

func (e ReviewCadence) IsValid() bool {
	switch e {
	case ReviewCadenceNone, ReviewCadenceAnnual, ReviewCadenceBiennial, ReviewCadenceOnDate:
		return true
	}
	return false
}

func (e ReviewCadence) String() string {
	return string(e)
}

func (e *ReviewCadence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewCadence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewCadence", str)
	}
	return nil
}

func (e ReviewCadence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewCadence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewCadence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskMitigation string

const (
	RiskMitigationFully    RiskMitigation = "FULLY"
	RiskMitigationPartly   RiskMitigation = "PARTLY"
	RiskMitigationNotAtAll RiskMitigation = "NOT_AT_ALL"
)

var AllRiskMitigation = []RiskMitigation{
	RiskMitigationFully,
	RiskMitigationPartly,
	RiskMitigationNotAtAll,
}

func (e RiskMitigation) IsValid() bool {
	switch e {
	case RiskMitigationFully, RiskMitigationPartly, RiskMitigationNotAtAll:
		return true
	}
	return false
}

func (e RiskMitigation) String() string {
	return string(e)
}

func (e *RiskMitigation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskMitigation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskMitigation", str)
	}
	return nil
}

func (e RiskMitigation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskMitigation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskMitigation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskRecipient string

const (
	RiskRecipientStaffOnly           RiskRecipient = "STAFF_ONLY"
	RiskRecipientUnknownPeople       RiskRecipient = "UNKNOWN_PEOPLE"
	RiskRecipientAnotherOrganisation RiskRecipient = "ANOTHER_ORGANISATION"
)

var AllRiskRecipient = []RiskRecipient{
	RiskRecipientStaffOnly,
	RiskRecipientUnknownPeople,
	RiskRecipientAnotherOrganisation,
}

func (e RiskRecipient) IsValid() bool {
	switch e {
	case RiskRecipientStaffOnly, RiskRecipientUnknownPeople, RiskRecipientAnotherOrganisation:
		return true
	}
	return false
}

func (e RiskRecipient) String() string {
	return string(e)
}

func (e *RiskRecipient) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskRecipient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskRecipient", str)
	}
	return nil
}

func (e RiskRecipient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskRecipient) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskRecipient) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskSuggestion string

const (
	RiskSuggestionNotificationLikelyRequired RiskSuggestion = "NOTIFICATION_LIKELY_REQUIRED"
	RiskSuggestionLowProbabilityOfCompromise RiskSuggestion = "LOW_PROBABILITY_OF_COMPROMISE"
)

var AllRiskSuggestion = []RiskSuggestion{
	RiskSuggestionNotificationLikelyRequired,
	RiskSuggestionLowProbabilityOfCompromise,
}

func (e RiskSuggestion) IsValid() bool {
	switch e {
	case RiskSuggestionNotificationLikelyRequired, RiskSuggestionLowProbabilityOfCompromise:
		return true
	}
	return false
}

func (e RiskSuggestion) String() string {
	return string(e)
}

func (e *RiskSuggestion) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskSuggestion(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskSuggestion", str)
	}
	return nil
}

func (e RiskSuggestion) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskSuggestion) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskSuggestion) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskViewed string

const (
	RiskViewedYes      RiskViewed = "YES"
	RiskViewedProbably RiskViewed = "PROBABLY"
	RiskViewedNo       RiskViewed = "NO"
)

var AllRiskViewed = []RiskViewed{
	RiskViewedYes,
	RiskViewedProbably,
	RiskViewedNo,
}

func (e RiskViewed) IsValid() bool {
	switch e {
	case RiskViewedYes, RiskViewedProbably, RiskViewedNo:
		return true
	}
	return false
}

func (e RiskViewed) String() string {
	return string(e)
}

func (e *RiskViewed) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskViewed(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskViewed", str)
	}
	return nil
}

func (e RiskViewed) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskViewed) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskViewed) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Sensitivity string

const (
	SensitivityStandard  Sensitivity = "STANDARD"
	SensitivitySensitive Sensitivity = "SENSITIVE"
)

var AllSensitivity = []Sensitivity{
	SensitivityStandard,
	SensitivitySensitive,
}

func (e Sensitivity) IsValid() bool {
	switch e {
	case SensitivityStandard, SensitivitySensitive:
		return true
	}
	return false
}

func (e Sensitivity) String() string {
	return string(e)
}

func (e *Sensitivity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sensitivity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sensitivity", str)
	}
	return nil
}

func (e Sensitivity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Sensitivity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Sensitivity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SignalType string

const (
	SignalTypeSignalTypeUnspecified    SignalType = "SIGNAL_TYPE_UNSPECIFIED"
	SignalTypeSignalTypeApprove        SignalType = "SIGNAL_TYPE_APPROVE"
	SignalTypeSignalTypeReject         SignalType = "SIGNAL_TYPE_REJECT"
	SignalTypeSignalTypeRequestChanges SignalType = "SIGNAL_TYPE_REQUEST_CHANGES"
	SignalTypeSignalTypeWithdraw       SignalType = "SIGNAL_TYPE_WITHDRAW"
	SignalTypeSignalTypeRetire         SignalType = "SIGNAL_TYPE_RETIRE"
)

var AllSignalType = []SignalType{
	SignalTypeSignalTypeUnspecified,
	SignalTypeSignalTypeApprove,
	SignalTypeSignalTypeReject,
	SignalTypeSignalTypeRequestChanges,
	SignalTypeSignalTypeWithdraw,
	SignalTypeSignalTypeRetire,
}

func (e SignalType) IsValid() bool {
	switch e {
	case SignalTypeSignalTypeUnspecified, SignalTypeSignalTypeApprove, SignalTypeSignalTypeReject, SignalTypeSignalTypeRequestChanges, SignalTypeSignalTypeWithdraw, SignalTypeSignalTypeRetire:
		return true
	}
	return false
}

func (e SignalType) String() string {
	return string(e)
}

func (e *SignalType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SignalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SignalType", str)
	}
	return nil
}

func (e SignalType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SignalType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SignalType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
