// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// SubmitAnonymousReport is the resolver for the submitAnonymousReport field.
func (r *mutationResolver) SubmitAnonymousReport(ctx context.Context, details ReportDetailsInput, passphrase string, attachments []*ReportAttachmentInput) (*AnonymousReportReceipt, error) {
	return r.SubmitAnonymousReportResolver(ctx, details, passphrase, attachments)
}

// CheckReport is the resolver for the checkReport field.
func (r *mutationResolver) CheckReport(ctx context.Context, caseCode string, passphrase string) (*ReporterView, error) {
	return r.CheckReportResolver(ctx, caseCode, passphrase)
}

// ReplyToReport is the resolver for the replyToReport field.
func (r *mutationResolver) ReplyToReport(ctx context.Context, caseCode string, passphrase string, body string) (*ReporterView, error) {
	return r.ReplyToReportResolver(ctx, caseCode, passphrase, body)
}

// SubmitNamedReport is the resolver for the submitNamedReport field.
func (r *mutationResolver) SubmitNamedReport(ctx context.Context, details ReportDetailsInput, attachments []*ReportAttachmentInput) (*NamedReportReceipt, error) {
	return r.SubmitNamedReportResolver(ctx, details, attachments)
}

// ReplyToMyReport is the resolver for the replyToMyReport field.
func (r *mutationResolver) ReplyToMyReport(ctx context.Context, caseID string, body string) (*ReporterView, error) {
	return r.ReplyToMyReportResolver(ctx, caseID, body)
}

// PostCaseMessage is the resolver for the postCaseMessage field.
func (r *mutationResolver) PostCaseMessage(ctx context.Context, caseID string, body string) (*ThreadMessage, error) {
	return r.PostCaseMessageResolver(ctx, caseID, body)
}

// AddCaseNote is the resolver for the addCaseNote field.
func (r *mutationResolver) AddCaseNote(ctx context.Context, caseID string, body string) (*CaseNote, error) {
	return r.AddCaseNoteResolver(ctx, caseID, body)
}

// AssignCase is the resolver for the assignCase field.
func (r *mutationResolver) AssignCase(ctx context.Context, caseID string, assigneeUserID *string) (*ReportCase, error) {
	return r.AssignCaseResolver(ctx, caseID, assigneeUserID)
}

// SetCaseStatus is the resolver for the setCaseStatus field.
func (r *mutationResolver) SetCaseStatus(ctx context.Context, caseID string, status CaseStatus) (*ReportCase, error) {
	return r.SetCaseStatusResolver(ctx, caseID, status)
}

// SetCaseDiscoveryDate is the resolver for the setCaseDiscoveryDate field.
func (r *mutationResolver) SetCaseDiscoveryDate(ctx context.Context, caseID string, discoveredOn string) (*ReportCase, error) {
	return r.SetCaseDiscoveryDateResolver(ctx, caseID, discoveredOn)
}

// RecordRiskAssessment is the resolver for the recordRiskAssessment field.
func (r *mutationResolver) RecordRiskAssessment(ctx context.Context, caseID string, factors RiskFactorsInput, decision BreachDecision, reason string) (*RiskAssessment, error) {
	return r.RecordRiskAssessmentResolver(ctx, caseID, factors, decision, reason)
}

// AddCaseNotice is the resolver for the addCaseNotice field.
func (r *mutationResolver) AddCaseNotice(ctx context.Context, caseID string, recipient NoticeRecipient, label *string, method *string) (*CaseNotice, error) {
	return r.AddCaseNoticeResolver(ctx, caseID, recipient, label, method)
}

// UpdateCaseNotice is the resolver for the updateCaseNotice field.
func (r *mutationResolver) UpdateCaseNotice(ctx context.Context, caseID string, noticeID string, status NoticeStatus, sentOn *string) (*CaseNotice, error) {
	return r.UpdateCaseNoticeResolver(ctx, caseID, noticeID, status, sentOn)
}

// CloseCase is the resolver for the closeCase field.
func (r *mutationResolver) CloseCase(ctx context.Context, caseID string, outcome CaseOutcome, correctiveActions []*CorrectiveActionInput, closingMessage *string) (*ReportCase, error) {
	return r.CloseCaseResolver(ctx, caseID, outcome, correctiveActions, closingMessage)
}

// MyReports is the resolver for the myReports field.
func (r *queryResolver) MyReports(ctx context.Context) ([]*MyReport, error) {
	return r.MyReportsResolver(ctx)
}

// MyReport is the resolver for the myReport field.
func (r *queryResolver) MyReport(ctx context.Context, caseID string) (*ReporterView, error) {
	return r.MyReportResolver(ctx, caseID)
}

// ReportCases is the resolver for the reportCases field.
func (r *queryResolver) ReportCases(ctx context.Context, statuses []CaseStatus, assigneeUserID *string) (*CaseQueue, error) {
	return r.ReportCasesResolver(ctx, statuses, assigneeUserID)
}

// ReportCase is the resolver for the reportCase field.
func (r *queryResolver) ReportCase(ctx context.Context, caseID string) (*ReportCase, error) {
	return r.ReportCaseResolver(ctx, caseID)
}

// ReportAttachment is the resolver for the reportAttachment field.
func (r *queryResolver) ReportAttachment(ctx context.Context, caseID string, attachmentID string) (*ReportAttachmentContent, error) {
	return r.ReportAttachmentResolver(ctx, caseID, attachmentID)
}
