// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// AddOrganization is the resolver for the addOrganization field.
func (r *mutationResolver) AddOrganization(ctx context.Context, input AddOrganizationInput) (*Organization, error) {
	return AddOrganizationResolver(ctx, r.SSOAdminClient, input)
}

// StartDomainVerification is the resolver for the startDomainVerification field.
func (r *mutationResolver) StartDomainVerification(ctx context.Context, domain string, rotate *bool) (*DomainVerification, error) {
	return StartDomainVerificationResolver(ctx, r.SSOAdminClient, domain, rotate)
}

// VerifyDomain is the resolver for the verifyDomain field.
func (r *mutationResolver) VerifyDomain(ctx context.Context, domain string) (*Organization, error) {
	return VerifyDomainResolver(ctx, r.SSOAdminClient, domain)
}

// ActivateOrganization is the resolver for the activateOrganization field.
func (r *mutationResolver) ActivateOrganization(ctx context.Context, domain string) (*Organization, error) {
	return ActivateOrganizationResolver(ctx, r.SSOAdminClient, domain)
}

// DisableOrganization is the resolver for the disableOrganization field.
func (r *mutationResolver) DisableOrganization(ctx context.Context, domain string) (*Organization, error) {
	return DisableOrganizationResolver(ctx, r.SSOAdminClient, domain)
}

// UpdateIDPConnection is the resolver for the updateIdPConnection field.
func (r *mutationResolver) UpdateIDPConnection(ctx context.Context, domain string, jitEnabled *bool, allowLocal *bool, secretRef *string, clientSecret *string) (*Organization, error) {
	return UpdateIdPConnectionResolver(ctx, r.SSOAdminClient, domain, jitEnabled, allowLocal, secretRef, clientSecret)
}

// ChangeOrgProtocol is the resolver for the changeOrgProtocol field.
func (r *mutationResolver) ChangeOrgProtocol(ctx context.Context, domain string, protocol string, config []*KeyValueInput, secretRef *string, clientSecret *string) (*Organization, error) {
	return ChangeOrgProtocolResolver(ctx, r.SSOAdminClient, domain, protocol, config, secretRef, clientSecret)
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, domain string) (bool, error) {
	return DeleteOrganizationResolver(ctx, r.SSOAdminClient, domain)
}

// AddGroupMapping is the resolver for the addGroupMapping field.
func (r *mutationResolver) AddGroupMapping(ctx context.Context, connectionID string, idpGroupClaimValue string, targetGroupID string) (*GroupMapping, error) {
	return AddGroupMappingResolver(ctx, r.SSOAdminClient, connectionID, idpGroupClaimValue, targetGroupID)
}

// DeleteGroupMapping is the resolver for the deleteGroupMapping field.
func (r *mutationResolver) DeleteGroupMapping(ctx context.Context, mappingID string) (bool, error) {
	return DeleteGroupMappingResolver(ctx, r.SSOAdminClient, mappingID)
}

// ForceRotateSpCertificate is the resolver for the forceRotateSpCertificate field.
func (r *mutationResolver) ForceRotateSpCertificate(ctx context.Context) (*SpCertificate, error) {
	return ForceRotateSpCertificateResolver(ctx, r.SSOAdminClient)
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*Organization, error) {
	return OrganizationsResolver(ctx, r.SSOAdminClient)
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, domain string) (*Organization, error) {
	return OrganizationResolver(ctx, r.SSOAdminClient, domain)
}

// SpCertificate is the resolver for the spCertificate field.
func (r *queryResolver) SpCertificate(ctx context.Context) (*SpCertificate, error) {
	return SpCertificateResolver(ctx, r.SSOAdminClient)
}

// SpCertificates is the resolver for the spCertificates field.
func (r *queryResolver) SpCertificates(ctx context.Context) ([]*SpCertificate, error) {
	return SpCertificatesResolver(ctx, r.SSOAdminClient)
}

// GroupMappings is the resolver for the groupMappings field.
func (r *queryResolver) GroupMappings(ctx context.Context, connectionID string) ([]*GroupMapping, error) {
	return GroupMappingsResolver(ctx, r.SSOAdminClient, connectionID)
}
