// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// AddOrganization is the resolver for the addOrganization field.
func (r *mutationResolver) AddOrganization(ctx context.Context, input AddOrganizationInput) (*Organization, error) {
	panic(fmt.Errorf("not implemented: AddOrganization - addOrganization"))
}

// StartDomainVerification is the resolver for the startDomainVerification field.
func (r *mutationResolver) StartDomainVerification(ctx context.Context, domain string, rotate *bool) (*DomainVerification, error) {
	panic(fmt.Errorf("not implemented: StartDomainVerification - startDomainVerification"))
}

// VerifyDomain is the resolver for the verifyDomain field.
func (r *mutationResolver) VerifyDomain(ctx context.Context, domain string) (*Organization, error) {
	panic(fmt.Errorf("not implemented: VerifyDomain - verifyDomain"))
}

// ActivateOrganization is the resolver for the activateOrganization field.
func (r *mutationResolver) ActivateOrganization(ctx context.Context, domain string) (*Organization, error) {
	panic(fmt.Errorf("not implemented: ActivateOrganization - activateOrganization"))
}

// DisableOrganization is the resolver for the disableOrganization field.
func (r *mutationResolver) DisableOrganization(ctx context.Context, domain string) (*Organization, error) {
	panic(fmt.Errorf("not implemented: DisableOrganization - disableOrganization"))
}

// UpdateIDPConnection is the resolver for the updateIdPConnection field.
func (r *mutationResolver) UpdateIDPConnection(ctx context.Context, domain string, jitEnabled *bool, allowLocal *bool) (*Organization, error) {
	panic(fmt.Errorf("not implemented: UpdateIDPConnection - updateIdPConnection"))
}

// ChangeOrgProtocol is the resolver for the changeOrgProtocol field.
func (r *mutationResolver) ChangeOrgProtocol(ctx context.Context, domain string, protocol string, config []*KeyValueInput, secretRef *string) (*Organization, error) {
	panic(fmt.Errorf("not implemented: ChangeOrgProtocol - changeOrgProtocol"))
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, domain string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteOrganization - deleteOrganization"))
}

// AddGroupMapping is the resolver for the addGroupMapping field.
func (r *mutationResolver) AddGroupMapping(ctx context.Context, connectionID string, idpGroupClaimValue string, targetGroupID string) (*GroupMapping, error) {
	panic(fmt.Errorf("not implemented: AddGroupMapping - addGroupMapping"))
}

// DeleteGroupMapping is the resolver for the deleteGroupMapping field.
func (r *mutationResolver) DeleteGroupMapping(ctx context.Context, mappingID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGroupMapping - deleteGroupMapping"))
}

// ForceRotateSpCertificate is the resolver for the forceRotateSpCertificate field.
func (r *mutationResolver) ForceRotateSpCertificate(ctx context.Context) (*SpCertificate, error) {
	panic(fmt.Errorf("not implemented: ForceRotateSpCertificate - forceRotateSpCertificate"))
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*Organization, error) {
	panic(fmt.Errorf("not implemented: Organizations - organizations"))
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, domain string) (*Organization, error) {
	panic(fmt.Errorf("not implemented: Organization - organization"))
}

// SpCertificate is the resolver for the spCertificate field.
func (r *queryResolver) SpCertificate(ctx context.Context) (*SpCertificate, error) {
	panic(fmt.Errorf("not implemented: SpCertificate - spCertificate"))
}

// SpCertificates is the resolver for the spCertificates field.
func (r *queryResolver) SpCertificates(ctx context.Context) ([]*SpCertificate, error) {
	panic(fmt.Errorf("not implemented: SpCertificates - spCertificates"))
}

// GroupMappings is the resolver for the groupMappings field.
func (r *queryResolver) GroupMappings(ctx context.Context, connectionID string) ([]*GroupMapping, error) {
	panic(fmt.Errorf("not implemented: GroupMappings - groupMappings"))
}
