// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
)

// SubmitWorkflow is the resolver for the submitWorkflow field.
func (r *mutationResolver) SubmitWorkflow(ctx context.Context, policyVersionID string, policyID string, groupID string, ancestorGroupIds []string) (*WorkflowSubmitResult, error) {
	panic(fmt.Errorf("not implemented: SubmitWorkflow - submitWorkflow"))
}

// SignalWorkflow is the resolver for the signalWorkflow field.
func (r *mutationResolver) SignalWorkflow(ctx context.Context, policyVersionID string, runID string, taskID string, signal SignalType, comment string) (bool, error) {
	panic(fmt.Errorf("not implemented: SignalWorkflow - signalWorkflow"))
}

// SwapAssignee is the resolver for the swapAssignee field.
func (r *mutationResolver) SwapAssignee(ctx context.Context, input SwapAssigneeInput) (*SwapAssigneeResult, error) {
	panic(fmt.Errorf("not implemented: SwapAssignee - swapAssignee"))
}

// BulkDecide is the resolver for the bulkDecide field.
func (r *mutationResolver) BulkDecide(ctx context.Context, input BulkDecideInput) (*BulkDecideResult, error) {
	panic(fmt.Errorf("not implemented: BulkDecide - bulkDecide"))
}

// CreateWorkflowDef is the resolver for the createWorkflowDef field.
func (r *mutationResolver) CreateWorkflowDef(ctx context.Context, name string, description *string, stages []*WorkflowStageInput) (*WorkflowDef, error) {
	panic(fmt.Errorf("not implemented: CreateWorkflowDef - createWorkflowDef"))
}

// UpdateWorkflowDef is the resolver for the updateWorkflowDef field.
func (r *mutationResolver) UpdateWorkflowDef(ctx context.Context, id string, name string, description *string, stages []*WorkflowStageInput) (*WorkflowDef, error) {
	panic(fmt.Errorf("not implemented: UpdateWorkflowDef - updateWorkflowDef"))
}

// ArchiveWorkflowDef is the resolver for the archiveWorkflowDef field.
func (r *mutationResolver) ArchiveWorkflowDef(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: ArchiveWorkflowDef - archiveWorkflowDef"))
}

// WorkflowStatus is the resolver for the workflowStatus field.
func (r *queryResolver) WorkflowStatus(ctx context.Context, policyVersionID string) (*WorkflowStatus, error) {
	panic(fmt.Errorf("not implemented: WorkflowStatus - workflowStatus"))
}

// PendingTasks is the resolver for the pendingTasks field.
func (r *queryResolver) PendingTasks(ctx context.Context) ([]*PendingTask, error) {
	panic(fmt.Errorf("not implemented: PendingTasks - pendingTasks"))
}

// UpcomingApprovals is the resolver for the upcomingApprovals field.
func (r *queryResolver) UpcomingApprovals(ctx context.Context) ([]*UpcomingApproval, error) {
	panic(fmt.Errorf("not implemented: UpcomingApprovals - upcomingApprovals"))
}

// EffectiveWorkflow is the resolver for the effectiveWorkflow field.
func (r *queryResolver) EffectiveWorkflow(ctx context.Context, policyID string) (*EffectiveWorkflow, error) {
	panic(fmt.Errorf("not implemented: EffectiveWorkflow - effectiveWorkflow"))
}

// AssignmentHistory is the resolver for the assignmentHistory field.
func (r *queryResolver) AssignmentHistory(ctx context.Context, policyVersionID string, stageIndex int) ([]*AssignmentHistoryEntry, error) {
	panic(fmt.Errorf("not implemented: AssignmentHistory - assignmentHistory"))
}

// StageEligibleAssignees is the resolver for the stageEligibleAssignees field.
func (r *queryResolver) StageEligibleAssignees(ctx context.Context, policyVersionID string, stageIndex int) (*StageEligibleAssignees, error) {
	panic(fmt.Errorf("not implemented: StageEligibleAssignees - stageEligibleAssignees"))
}

// WorkflowDefs is the resolver for the workflowDefs field.
func (r *queryResolver) WorkflowDefs(ctx context.Context) ([]*WorkflowDef, error) {
	panic(fmt.Errorf("not implemented: WorkflowDefs - workflowDefs"))
}

// WorkflowDef is the resolver for the workflowDef field.
func (r *queryResolver) WorkflowDef(ctx context.Context, id string) (*WorkflowDef, error) {
	panic(fmt.Errorf("not implemented: WorkflowDef - workflowDef"))
}
